# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormControleioCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ct_MainClientes(object):
    def setupUi(self, ct_MainClientes):
        ct_MainClientes.setObjectName("ct_MainClientes")
        ct_MainClientes.resize(1498, 861)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/clientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ct_MainClientes.setWindowIcon(icon)
        ct_MainClientes.setStyleSheet("border:none;\n"
"text-transform: uppercase;\n"
"")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(ct_MainClientes)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(ct_MainClientes)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.frameMainClientes = QtWidgets.QFrame(self.widget)
        self.frameMainClientes.setMinimumSize(QtCore.QSize(1450, 0))
        self.frameMainClientes.setStyleSheet("\n"
"QFrame#frameMainClientes{\n"
"text-transform: uppercase;\n"
"border:1px solid blue;\n"
"background-color: rgb(247, 247, 247);\n"
"}\n"
"")
        self.frameMainClientes.setObjectName("frameMainClientes")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameMainClientes)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr_TituloClientes = QtWidgets.QFrame(self.frameMainClientes)
        self.fr_TituloClientes.setMinimumSize(QtCore.QSize(0, 45))
        self.fr_TituloClientes.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fr_TituloClientes.setStyleSheet("QFrame#fr_TituloClientes{\n"
"color:red;\n"
"border: none;\n"
"background-color:#2408D4;}\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.fr_TituloClientes.setObjectName("fr_TituloClientes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_TituloClientes)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_tituloClientes = QtWidgets.QLabel(self.fr_TituloClientes)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lb_tituloClientes.setFont(font)
        self.lb_tituloClientes.setStyleSheet("")
        self.lb_tituloClientes.setObjectName("lb_tituloClientes")
        self.horizontalLayout_3.addWidget(self.lb_tituloClientes)
        self.verticalLayout_2.addWidget(self.fr_TituloClientes)
        self.ct_containerClientes = QtWidgets.QFrame(self.frameMainClientes)
        self.ct_containerClientes.setStyleSheet("border: none")
        self.ct_containerClientes.setObjectName("ct_containerClientes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ct_containerClientes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.ct_containerClientes)
        self.frame.setMinimumSize(QtCore.QSize(200, 120))
        self.frame.setStyleSheet("QLabel{\n"
"    font: 26pt \"MS Shell Dlg 2\";\n"
"text-transform: uppercase;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Lb_nome = QtWidgets.QLabel(self.frame)
        self.Lb_nome.setGeometry(QtCore.QRect(130, 20, 1181, 81))
        self.Lb_nome.setStyleSheet("border-bottom:1px solid")
        self.Lb_nome.setText("")
        self.Lb_nome.setObjectName("Lb_nome")
        self.lb_fotoCliente = QtWidgets.QLabel(self.frame)
        self.lb_fotoCliente.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.lb_fotoCliente.setMinimumSize(QtCore.QSize(100, 100))
        self.lb_fotoCliente.setMaximumSize(QtCore.QSize(100, 100))
        self.lb_fotoCliente.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.994318, x2:1, y2:1, stop:0 rgba(0, 0, 0, 100), stop:1 rgba(255, 255, 255, 255));")
        self.lb_fotoCliente.setText("")
        self.lb_fotoCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_fotoCliente.setObjectName("lb_fotoCliente")
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_edita = QtWidgets.QFrame(self.ct_containerClientes)
        self.frame_edita.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color: rgb(0, 85, 255);\n"
"padding:15px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_edita.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_edita.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_edita.setObjectName("frame_edita")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_edita)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fr_TopoMenuClientes = QtWidgets.QFrame(self.frame_edita)
        self.fr_TopoMenuClientes.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fr_TopoMenuClientes.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_TopoMenuClientes.setObjectName("fr_TopoMenuClientes")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_TopoMenuClientes)
        self.horizontalLayout.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tx_BuscaClientes = QtWidgets.QLineEdit(self.fr_TopoMenuClientes)
        self.tx_BuscaClientes.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tx_BuscaClientes.setFont(font)
        self.tx_BuscaClientes.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_BuscaClientes.setStyleSheet("\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"padding:10px\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(226, 226, 226);\n"
"}\n"
"")
        self.tx_BuscaClientes.setFrame(True)
        self.tx_BuscaClientes.setObjectName("tx_BuscaClientes")
        self.horizontalLayout.addWidget(self.tx_BuscaClientes)
        self.bt_BuscaClientes = QtWidgets.QPushButton(self.fr_TopoMenuClientes)
        self.bt_BuscaClientes.setMinimumSize(QtCore.QSize(40, 45))
        self.bt_BuscaClientes.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bt_BuscaClientes.setFont(font)
        self.bt_BuscaClientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_BuscaClientes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_BuscaClientes.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bt_BuscaClientes.setStyleSheet("QPushButton {\n"
"background-color: #41CD52;\n"
"color:white;\n"
"    font: 75 28pt \"Tahoma\";\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_BuscaClientes.setObjectName("bt_BuscaClientes")
        self.horizontalLayout.addWidget(self.bt_BuscaClientes)
        self.horizontalLayout_2.addWidget(self.fr_TopoMenuClientes)
        self.bt_novo = QtWidgets.QPushButton(self.frame_edita)
        self.bt_novo.setMinimumSize(QtCore.QSize(0, 60))
        self.bt_novo.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/cadastro clientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_novo.setIcon(icon1)
        self.bt_novo.setIconSize(QtCore.QSize(30, 30))
        self.bt_novo.setObjectName("bt_novo")
        self.horizontalLayout_2.addWidget(self.bt_novo)
        self.bt_alterar = QtWidgets.QPushButton(self.frame_edita)
        self.bt_alterar.setMinimumSize(QtCore.QSize(0, 60))
        self.bt_alterar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_alterar.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/edita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_alterar.setIcon(icon2)
        self.bt_alterar.setIconSize(QtCore.QSize(30, 30))
        self.bt_alterar.setObjectName("bt_alterar")
        self.horizontalLayout_2.addWidget(self.bt_alterar)
        self.bt_Excluir = QtWidgets.QPushButton(self.frame_edita)
        self.bt_Excluir.setMinimumSize(QtCore.QSize(0, 60))
        self.bt_Excluir.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Excluir.setIcon(icon3)
        self.bt_Excluir.setIconSize(QtCore.QSize(30, 30))
        self.bt_Excluir.setObjectName("bt_Excluir")
        self.horizontalLayout_2.addWidget(self.bt_Excluir)
        self.bt_Imprimir = QtWidgets.QPushButton(self.frame_edita)
        self.bt_Imprimir.setMinimumSize(QtCore.QSize(0, 60))
        self.bt_Imprimir.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/impressao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Imprimir.setIcon(icon4)
        self.bt_Imprimir.setIconSize(QtCore.QSize(30, 30))
        self.bt_Imprimir.setObjectName("bt_Imprimir")
        self.horizontalLayout_2.addWidget(self.bt_Imprimir)
        self.bt_WhatssapEnvio = QtWidgets.QPushButton(self.frame_edita)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/whatsapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_WhatssapEnvio.setIcon(icon5)
        self.bt_WhatssapEnvio.setIconSize(QtCore.QSize(30, 30))
        self.bt_WhatssapEnvio.setObjectName("bt_WhatssapEnvio")
        self.horizontalLayout_2.addWidget(self.bt_WhatssapEnvio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_edita)
        self.frame_2 = QtWidgets.QFrame(self.ct_containerClientes)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget_usuario_2 = QtWidgets.QTableWidget(self.frame_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 103, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 103, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 103, 154))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tableWidget_usuario_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget_usuario_2.setFont(font)
        self.tableWidget_usuario_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget_usuario_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidget_usuario_2.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"  border: 0px solid black;\n"
"border-bottom:1px solid;\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"  background-color: blue;\n"
"  color: white;\n"
"}\n"
"")
        self.tableWidget_usuario_2.setAutoScrollMargin(20)
        self.tableWidget_usuario_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_usuario_2.setAlternatingRowColors(False)
        self.tableWidget_usuario_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_usuario_2.setShowGrid(False)
        self.tableWidget_usuario_2.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget_usuario_2.setWordWrap(True)
        self.tableWidget_usuario_2.setObjectName("tableWidget_usuario_2")
        self.tableWidget_usuario_2.setColumnCount(5)
        self.tableWidget_usuario_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_usuario_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_usuario_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_usuario_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableWidget_usuario_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_usuario_2.setHorizontalHeaderItem(4, item)
        self.tableWidget_usuario_2.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_usuario_2.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_usuario_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_usuario_2.verticalHeader().setVisible(False)
        self.tableWidget_usuario_2.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget_usuario_2.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout_6.addWidget(self.tableWidget_usuario_2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.ct_containerClientes)
        self.ct_containerClientes.raise_()
        self.fr_TituloClientes.raise_()
        self.horizontalLayout_4.addWidget(self.frameMainClientes)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.widget)

        self.retranslateUi(ct_MainClientes)
        QtCore.QMetaObject.connectSlotsByName(ct_MainClientes)
        ct_MainClientes.setTabOrder(self.tx_BuscaClientes, self.bt_novo)
        ct_MainClientes.setTabOrder(self.bt_novo, self.bt_alterar)
        ct_MainClientes.setTabOrder(self.bt_alterar, self.bt_Excluir)
        ct_MainClientes.setTabOrder(self.bt_Excluir, self.bt_Imprimir)

    def retranslateUi(self, ct_MainClientes):
        _translate = QtCore.QCoreApplication.translate
        ct_MainClientes.setWindowTitle(_translate("ct_MainClientes", "BuscaClientes"))
        self.lb_tituloClientes.setText(_translate("ct_MainClientes", "CONTROLEIO DE CLIENTES"))
        self.tx_BuscaClientes.setPlaceholderText(_translate("ct_MainClientes", "BUSCA CLIENTES"))
        self.bt_BuscaClientes.setToolTip(_translate("ct_MainClientes", "BUSCAR"))
        self.bt_BuscaClientes.setStatusTip(_translate("ct_MainClientes", "BUSCAR CLIENTES"))
        self.bt_BuscaClientes.setText(_translate("ct_MainClientes", ">"))
        self.bt_novo.setText(_translate("ct_MainClientes", "novos clientes"))
        self.bt_alterar.setText(_translate("ct_MainClientes", "alterar"))
        self.bt_Excluir.setText(_translate("ct_MainClientes", "excluir"))
        self.bt_Imprimir.setText(_translate("ct_MainClientes", "imprimir"))
        self.bt_WhatssapEnvio.setText(_translate("ct_MainClientes", "mensagem"))
        self.tableWidget_usuario_2.setSortingEnabled(False)
        item = self.tableWidget_usuario_2.horizontalHeaderItem(0)
        item.setText(_translate("ct_MainClientes", "ID"))
        item = self.tableWidget_usuario_2.horizontalHeaderItem(1)
        item.setText(_translate("ct_MainClientes", "NOME"))
        item = self.tableWidget_usuario_2.horizontalHeaderItem(2)
        item.setText(_translate("ct_MainClientes", "TELEFONE"))
        item = self.tableWidget_usuario_2.horizontalHeaderItem(3)
        item.setText(_translate("ct_MainClientes", "EMAIL"))
        item = self.tableWidget_usuario_2.horizontalHeaderItem(4)
        item.setText(_translate("ct_MainClientes", "imprimir"))
