# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormAlteraQuantidade.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAlteraQuantidade(object):
    def setupUi(self, FormAlteraQuantidade):
        FormAlteraQuantidade.setObjectName("FormAlteraQuantidade")
        FormAlteraQuantidade.setWindowModality(QtCore.Qt.ApplicationModal)
        FormAlteraQuantidade.resize(273, 152)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormAlteraQuantidade)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(FormAlteraQuantidade)
        self.widget.setStyleSheet("QWidget#widget{\n"
"text-transform: uppercase;\n"
"border:1px solid blue;\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fr_TituloClientes = QtWidgets.QFrame(self.widget_2)
        self.fr_TituloClientes.setMinimumSize(QtCore.QSize(0, 45))
        self.fr_TituloClientes.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fr_TituloClientes.setStyleSheet("QFrame#fr_TituloClientes{\n"
"color:red;\n"
"border: none;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(0, 0, 255, 212), stop:1 rgba(255, 255, 255, 255));}")
        self.fr_TituloClientes.setObjectName("fr_TituloClientes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_TituloClientes)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_tituloClientes = QtWidgets.QLabel(self.fr_TituloClientes)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lb_tituloClientes.setFont(font)
        self.lb_tituloClientes.setStyleSheet("color: white;\n"
"background-color:none;\n"
"font: 75 25pt \"MS Shell Dlg 2\";")
        self.lb_tituloClientes.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_tituloClientes.setObjectName("lb_tituloClientes")
        self.horizontalLayout_3.addWidget(self.lb_tituloClientes)
        self.verticalLayout_3.addWidget(self.fr_TituloClientes)
        self.db_Quant = QtWidgets.QDoubleSpinBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.db_Quant.setFont(font)
        self.db_Quant.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.db_Quant.setWrapping(False)
        self.db_Quant.setAlignment(QtCore.Qt.AlignCenter)
        self.db_Quant.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_Quant.setAccelerated(False)
        self.db_Quant.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.db_Quant.setKeyboardTracking(True)
        self.db_Quant.setProperty("showGroupSeparator", False)
        self.db_Quant.setPrefix("")
        self.db_Quant.setSuffix("")
        self.db_Quant.setMaximum(9999999999.0)
        self.db_Quant.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.db_Quant.setProperty("value", 1.0)
        self.db_Quant.setObjectName("db_Quant")
        self.verticalLayout_3.addWidget(self.db_Quant)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(FormAlteraQuantidade)
        QtCore.QMetaObject.connectSlotsByName(FormAlteraQuantidade)

    def retranslateUi(self, FormAlteraQuantidade):
        _translate = QtCore.QCoreApplication.translate
        FormAlteraQuantidade.setWindowTitle(_translate("FormAlteraQuantidade", "Form"))
        self.lb_tituloClientes.setText(_translate("FormAlteraQuantidade", "QUANTIDADE"))
