# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormContaReceber.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormContaReceber(object):
    def setupUi(self, FormContaReceber):
        FormContaReceber.setObjectName("FormContaReceber")
        FormContaReceber.resize(1725, 826)
        FormContaReceber.setMinimumSize(QtCore.QSize(0, 20))
        FormContaReceber.setStyleSheet("QWidget{text-transform: uppercase;\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"    color: rgb(0, 0, 0);\n"
"border: none;\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"padding:6px\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.widget_6 = QtWidgets.QWidget(FormContaReceber)
        self.widget_6.setGeometry(QtCore.QRect(10, 10, 1500, 700))
        self.widget_6.setMinimumSize(QtCore.QSize(1500, 700))
        self.widget_6.setMaximumSize(QtCore.QSize(800, 700))
        self.widget_6.setStyleSheet("QWidget#widget_6{\n"
"border:1px solid blue;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"color:red;\n"
"border: none;\n"
"background-color:#2408D4;}\n"
"\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.tabWidget = QtWidgets.QTabWidget(self.widget_6)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border: 1px solid lightgray;\n"
"  top:-1px; \n"
"  background: rgb(245, 245, 245);; \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background: rgb(230, 230, 230); \n"
"  border: 1px solid lightgray; \n"
"  padding: 15px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border:1px solid;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.receber = QtWidgets.QWidget()
        self.receber.setObjectName("receber")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.receber)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tb_geral = QtWidgets.QTableWidget(self.receber)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tb_geral.setPalette(palette)
        self.tb_geral.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tb_geral.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"  border: 0px solid black;\n"
"border-bottom:1px solid;\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"  background-color: blue;\n"
"  color: white;\n"
"}\n"
"")
        self.tb_geral.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_geral.setTabKeyNavigation(False)
        self.tb_geral.setProperty("showDropIndicator", True)
        self.tb_geral.setDragDropOverwriteMode(False)
        self.tb_geral.setAlternatingRowColors(False)
        self.tb_geral.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tb_geral.setShowGrid(False)
        self.tb_geral.setGridStyle(QtCore.Qt.SolidLine)
        self.tb_geral.setObjectName("tb_geral")
        self.tb_geral.setColumnCount(9)
        self.tb_geral.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tb_geral.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_geral.setHorizontalHeaderItem(8, item)
        self.tb_geral.horizontalHeader().setDefaultSectionSize(150)
        self.tb_geral.horizontalHeader().setHighlightSections(False)
        self.tb_geral.horizontalHeader().setStretchLastSection(False)
        self.tb_geral.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tb_geral)
        self.frame_6 = QtWidgets.QFrame(self.receber)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.valoGeral = QtWidgets.QDoubleSpinBox(self.frame_6)
        self.valoGeral.setMinimumSize(QtCore.QSize(200, 0))
        self.valoGeral.setFocusPolicy(QtCore.Qt.NoFocus)
        self.valoGeral.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.valoGeral.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.valoGeral.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.valoGeral.setProperty("showGroupSeparator", True)
        self.valoGeral.setMaximum(99999999999999.0)
        self.valoGeral.setObjectName("valoGeral")
        self.horizontalLayout_5.addWidget(self.valoGeral)
        self.verticalLayout.addWidget(self.frame_6)
        self.tabWidget.addTab(self.receber, "")
        self.receber1 = QtWidgets.QWidget()
        self.receber1.setObjectName("receber1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.receber1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.receber1)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tx_buscarCliente = QtWidgets.QLineEdit(self.frame_2)
        self.tx_buscarCliente.setMinimumSize(QtCore.QSize(0, 30))
        self.tx_buscarCliente.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tx_buscarCliente.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"padding:6px\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"")
        self.tx_buscarCliente.setObjectName("tx_buscarCliente")
        self.horizontalLayout_2.addWidget(self.tx_buscarCliente)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lb_CodigoClinte = QtWidgets.QLabel(self.frame_2)
        self.lb_CodigoClinte.setMinimumSize(QtCore.QSize(120, 0))
        self.lb_CodigoClinte.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 127);")
        self.lb_CodigoClinte.setText("")
        self.lb_CodigoClinte.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_CodigoClinte.setObjectName("lb_CodigoClinte")
        self.horizontalLayout_2.addWidget(self.lb_CodigoClinte)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lb_NomeCliente = QtWidgets.QLabel(self.frame_2)
        self.lb_NomeCliente.setMinimumSize(QtCore.QSize(450, 0))
        self.lb_NomeCliente.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 127);")
        self.lb_NomeCliente.setText("")
        self.lb_NomeCliente.setObjectName("lb_NomeCliente")
        self.horizontalLayout_2.addWidget(self.lb_NomeCliente)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.progressBar.setMaximumSize(QtCore.QSize(400, 30))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #FFD700, stop: 1 #FF8C00);\n"
"    width: 10px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.tab_receber = QtWidgets.QTableWidget(self.receber1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tab_receber.setPalette(palette)
        self.tab_receber.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tab_receber.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tab_receber.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"")
        self.tab_receber.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_receber.setTabKeyNavigation(True)
        self.tab_receber.setProperty("showDropIndicator", True)
        self.tab_receber.setDragDropOverwriteMode(False)
        self.tab_receber.setAlternatingRowColors(False)
        self.tab_receber.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab_receber.setShowGrid(True)
        self.tab_receber.setGridStyle(QtCore.Qt.SolidLine)
        self.tab_receber.setObjectName("tab_receber")
        self.tab_receber.setColumnCount(10)
        self.tab_receber.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tab_receber.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_receber.setHorizontalHeaderItem(9, item)
        self.tab_receber.horizontalHeader().setDefaultSectionSize(150)
        self.tab_receber.horizontalHeader().setHighlightSections(False)
        self.tab_receber.horizontalHeader().setStretchLastSection(False)
        self.tab_receber.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tab_receber)
        self.frame_5 = QtWidgets.QFrame(self.receber1)
        self.frame_5.setStyleSheet("border:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setStyleSheet("QFrame{\n"
"border:none\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color: rgb(0, 85, 255);\n"
"padding:15px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_incluirReceber = QtWidgets.QPushButton(self.frame)
        self.bt_incluirReceber.setMinimumSize(QtCore.QSize(0, 55))
        self.bt_incluirReceber.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_incluirReceber.setObjectName("bt_incluirReceber")
        self.horizontalLayout.addWidget(self.bt_incluirReceber)
        self.bt_AlteraREceber = QtWidgets.QPushButton(self.frame)
        self.bt_AlteraREceber.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_AlteraREceber.setObjectName("bt_AlteraREceber")
        self.horizontalLayout.addWidget(self.bt_AlteraREceber)
        self.bt_apagar = QtWidgets.QPushButton(self.frame)
        self.bt_apagar.setObjectName("bt_apagar")
        self.horizontalLayout.addWidget(self.bt_apagar)
        self.bt_receber = QtWidgets.QPushButton(self.frame)
        self.bt_receber.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_receber.setObjectName("bt_receber")
        self.horizontalLayout.addWidget(self.bt_receber)
        self.bt_marcatodos = QtWidgets.QPushButton(self.frame)
        self.bt_marcatodos.setObjectName("bt_marcatodos")
        self.horizontalLayout.addWidget(self.bt_marcatodos)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tx_valorTotalparcela = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.tx_valorTotalparcela.setMinimumSize(QtCore.QSize(100, 0))
        self.tx_valorTotalparcela.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_valorTotalparcela.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.tx_valorTotalparcela.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_valorTotalparcela.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_valorTotalparcela.setProperty("showGroupSeparator", True)
        self.tx_valorTotalparcela.setDecimals(4)
        self.tx_valorTotalparcela.setMaximum(99999999.0)
        self.tx_valorTotalparcela.setObjectName("tx_valorTotalparcela")
        self.verticalLayout_2.addWidget(self.tx_valorTotalparcela)
        self.tx_valorJuros = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.tx_valorJuros.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_valorJuros.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.tx_valorJuros.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_valorJuros.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_valorJuros.setProperty("showGroupSeparator", True)
        self.tx_valorJuros.setDecimals(4)
        self.tx_valorJuros.setMinimum(0.0)
        self.tx_valorJuros.setMaximum(9999999.0)
        self.tx_valorJuros.setProperty("value", 0.0)
        self.tx_valorJuros.setObjectName("tx_valorJuros")
        self.verticalLayout_2.addWidget(self.tx_valorJuros)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.tabWidget.addTab(self.receber1, "")
        self.recebidos = QtWidgets.QWidget()
        self.recebidos.setObjectName("recebidos")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.recebidos)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.wb_recebidos = QtWidgets.QWidget(self.recebidos)
        self.wb_recebidos.setMinimumSize(QtCore.QSize(0, 0))
        self.wb_recebidos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wb_recebidos.setStyleSheet("QWidget{\n"
"background-color: rgb(231, 231, 231);\n"
"border:0px solid blue;\n"
"text-transform: uppercase;\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color: rgb(0, 85, 255);\n"
"padding:15px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"")
        self.wb_recebidos.setObjectName("wb_recebidos")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.wb_recebidos)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.wb_recebidos)
        self.frame_14.setStyleSheet("QFrame\n"
"{background: #eaeaea;\n"
"border: none\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color:black;\n"
"border: none;\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 127);\n"
"border:1px solid;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"QDoubleSpinBox{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_nome = QtWidgets.QLabel(self.frame_14)
        self.lb_nome.setMinimumSize(QtCore.QSize(0, 20))
        self.lb_nome.setStyleSheet("border:none;")
        self.lb_nome.setText("")
        self.lb_nome.setObjectName("lb_nome")
        self.verticalLayout_7.addWidget(self.lb_nome)
        self.tab_recebidos = QtWidgets.QTableWidget(self.frame_14)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tab_recebidos.setPalette(palette)
        self.tab_recebidos.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tab_recebidos.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"  border: 0px solid black;\n"
"border-bottom:1px solid;\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"  background-color: blue;\n"
"  color: white;\n"
"}\n"
"")
        self.tab_recebidos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_recebidos.setTabKeyNavigation(False)
        self.tab_recebidos.setProperty("showDropIndicator", True)
        self.tab_recebidos.setDragDropOverwriteMode(False)
        self.tab_recebidos.setAlternatingRowColors(False)
        self.tab_recebidos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tab_recebidos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab_recebidos.setShowGrid(False)
        self.tab_recebidos.setGridStyle(QtCore.Qt.SolidLine)
        self.tab_recebidos.setObjectName("tab_recebidos")
        self.tab_recebidos.setColumnCount(10)
        self.tab_recebidos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tab_recebidos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_recebidos.setHorizontalHeaderItem(9, item)
        self.tab_recebidos.horizontalHeader().setDefaultSectionSize(150)
        self.tab_recebidos.horizontalHeader().setHighlightSections(False)
        self.tab_recebidos.horizontalHeader().setStretchLastSection(False)
        self.tab_recebidos.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tab_recebidos)
        self.frame_3 = QtWidgets.QFrame(self.frame_14)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_SalvarPagamento_2 = QtWidgets.QPushButton(self.frame_3)
        self.bt_SalvarPagamento_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.bt_SalvarPagamento_2.setFont(font)
        self.bt_SalvarPagamento_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_SalvarPagamento_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_SalvarPagamento_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_SalvarPagamento_2.setStyleSheet("")
        self.bt_SalvarPagamento_2.setIconSize(QtCore.QSize(75, 35))
        self.bt_SalvarPagamento_2.setObjectName("bt_SalvarPagamento_2")
        self.horizontalLayout_6.addWidget(self.bt_SalvarPagamento_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.db_Nominmal = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.db_Nominmal.setMinimumSize(QtCore.QSize(100, 20))
        self.db_Nominmal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_Nominmal.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.db_Nominmal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_Nominmal.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_Nominmal.setProperty("showGroupSeparator", True)
        self.db_Nominmal.setDecimals(4)
        self.db_Nominmal.setMinimum(0.0)
        self.db_Nominmal.setMaximum(1e+19)
        self.db_Nominmal.setProperty("value", 0.0)
        self.db_Nominmal.setObjectName("db_Nominmal")
        self.horizontalLayout_6.addWidget(self.db_Nominmal)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.tx_valorTotalparcela_2 = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.tx_valorTotalparcela_2.setMinimumSize(QtCore.QSize(100, 20))
        self.tx_valorTotalparcela_2.setMaximumSize(QtCore.QSize(380, 16777215))
        self.tx_valorTotalparcela_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_valorTotalparcela_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.tx_valorTotalparcela_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_valorTotalparcela_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_valorTotalparcela_2.setProperty("showGroupSeparator", True)
        self.tx_valorTotalparcela_2.setDecimals(4)
        self.tx_valorTotalparcela_2.setMaximum(1e+18)
        self.tx_valorTotalparcela_2.setObjectName("tx_valorTotalparcela_2")
        self.horizontalLayout_6.addWidget(self.tx_valorTotalparcela_2)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.verticalLayout_8.addWidget(self.wb_recebidos)
        self.tabWidget.addTab(self.recebidos, "")
        self.atrasado = QtWidgets.QWidget()
        self.atrasado.setObjectName("atrasado")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.atrasado)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tb_atrasado = QtWidgets.QTableWidget(self.atrasado)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tb_atrasado.setPalette(palette)
        self.tb_atrasado.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tb_atrasado.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"  border: 0px solid black;\n"
"border-bottom:1px solid;\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"  background-color: blue;\n"
"  color: white;\n"
"}\n"
"")
        self.tb_atrasado.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_atrasado.setTabKeyNavigation(False)
        self.tb_atrasado.setProperty("showDropIndicator", True)
        self.tb_atrasado.setDragDropOverwriteMode(False)
        self.tb_atrasado.setAlternatingRowColors(False)
        self.tb_atrasado.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tb_atrasado.setShowGrid(False)
        self.tb_atrasado.setGridStyle(QtCore.Qt.SolidLine)
        self.tb_atrasado.setObjectName("tb_atrasado")
        self.tb_atrasado.setColumnCount(9)
        self.tb_atrasado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tb_atrasado.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_atrasado.setHorizontalHeaderItem(8, item)
        self.tb_atrasado.horizontalHeader().setDefaultSectionSize(150)
        self.tb_atrasado.horizontalHeader().setHighlightSections(False)
        self.tb_atrasado.horizontalHeader().setStretchLastSection(False)
        self.tb_atrasado.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.tb_atrasado)
        self.frame_8 = QtWidgets.QFrame(self.atrasado)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.db_atrasado = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.db_atrasado.setMinimumSize(QtCore.QSize(200, 0))
        self.db_atrasado.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_atrasado.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"font: 12pt \"Segoe UI\";")
        self.db_atrasado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_atrasado.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_atrasado.setProperty("showGroupSeparator", True)
        self.db_atrasado.setMaximum(99999999999999.0)
        self.db_atrasado.setObjectName("db_atrasado")
        self.horizontalLayout_7.addWidget(self.db_atrasado)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.tabWidget.addTab(self.atrasado, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.wb_incluirParcelas = QtWidgets.QWidget(FormContaReceber)
        self.wb_incluirParcelas.setGeometry(QtCore.QRect(1520, 90, 848, 421))
        self.wb_incluirParcelas.setMinimumSize(QtCore.QSize(848, 0))
        self.wb_incluirParcelas.setMaximumSize(QtCore.QSize(700, 500))
        self.wb_incluirParcelas.setStyleSheet("QWidget{\n"
"background-color: rgb(231, 231, 231);\n"
"border:1px solid blue;\n"
"}\n"
"QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color: rgb(0, 85, 255);\n"
"padding:15px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"")
        self.wb_incluirParcelas.setObjectName("wb_incluirParcelas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wb_incluirParcelas)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.wb_incluirParcelas)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_10.setStyleSheet("\n"
"QFrame#frame_10{\n"
"color:red;\n"
"border: none;\n"
"background-color:#2408D4;}\n"
"\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setStyleSheet("border:none")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.wb_incluirParcelas)
        self.frame_11.setStyleSheet("QFrame\n"
"{background: #eaeaea;\n"
"border: none\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color:black;\n"
"border: none;\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox{\n"
"background-color: rgb(255, 255, 127);\n"
"border:1px solid;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"QDoubleSpinBox{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.tx_descricaocliente = QtWidgets.QLineEdit(self.frame_11)
        self.tx_descricaocliente.setGeometry(QtCore.QRect(220, 30, 481, 31))
        self.tx_descricaocliente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_descricaocliente.setObjectName("tx_descricaocliente")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setGeometry(QtCore.QRect(120, 10, 121, 20))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 131, 16))
        self.label_8.setObjectName("label_8")
        self.dt_emissao = QtWidgets.QDateEdit(self.frame_11)
        self.dt_emissao.setGeometry(QtCore.QRect(470, 90, 141, 31))
        self.dt_emissao.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dt_emissao.setStyleSheet("QDateEdit {\n"
"\n"
"    border: 2px solid lightgray;\n"
"    border-radius: 5px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
" \n"
"\n"
" \n"
"QDateEdit::drop-down:hover {\n"
"    /* Does this work with QDateEdit??? */\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d8d7d7, stop: 1 #e9e9e9);\n"
"}")
        self.dt_emissao.setCalendarPopup(True)
        self.dt_emissao.setObjectName("dt_emissao")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setGeometry(QtCore.QRect(470, 70, 111, 16))
        self.label_10.setObjectName("label_10")
        self.tx_incluirValorpagamento = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.tx_incluirValorpagamento.setGeometry(QtCore.QRect(20, 200, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        self.tx_incluirValorpagamento.setFont(font)
        self.tx_incluirValorpagamento.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";")
        self.tx_incluirValorpagamento.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_incluirValorpagamento.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_incluirValorpagamento.setProperty("showGroupSeparator", True)
        self.tx_incluirValorpagamento.setMaximum(99999.0)
        self.tx_incluirValorpagamento.setProperty("value", 0.0)
        self.tx_incluirValorpagamento.setObjectName("tx_incluirValorpagamento")
        self.label_12 = QtWidgets.QLabel(self.frame_11)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_12.setObjectName("label_12")
        self.tx_Numeronota = QtWidgets.QLineEdit(self.frame_11)
        self.tx_Numeronota.setGeometry(QtCore.QRect(20, 30, 91, 31))
        self.tx_Numeronota.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tx_Numeronota.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_Numeronota.setObjectName("tx_Numeronota")
        self.tx_codCliente = QtWidgets.QLineEdit(self.frame_11)
        self.tx_codCliente.setGeometry(QtCore.QRect(120, 30, 91, 31))
        self.tx_codCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_codCliente.setObjectName("tx_codCliente")
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        self.label_9.setGeometry(QtCore.QRect(220, 10, 121, 20))
        self.label_9.setObjectName("label_9")
        self.tx_codPArcelas = QtWidgets.QLineEdit(self.frame_11)
        self.tx_codPArcelas.setGeometry(QtCore.QRect(20, 90, 91, 31))
        self.tx_codPArcelas.setObjectName("tx_codPArcelas")
        self.label_13 = QtWidgets.QLabel(self.frame_11)
        self.label_13.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.label_13.setObjectName("label_13")
        self.tx_descricaoparcelas = QtWidgets.QLineEdit(self.frame_11)
        self.tx_descricaoparcelas.setGeometry(QtCore.QRect(130, 90, 141, 31))
        self.tx_descricaoparcelas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_descricaoparcelas.setObjectName("tx_descricaoparcelas")
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setGeometry(QtCore.QRect(130, 70, 131, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setGeometry(QtCore.QRect(280, 70, 131, 16))
        self.label_15.setObjectName("label_15")
        self.tx_quantPArcelas = QtWidgets.QLineEdit(self.frame_11)
        self.tx_quantPArcelas.setGeometry(QtCore.QRect(280, 90, 91, 31))
        self.tx_quantPArcelas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_quantPArcelas.setMaxLength(10)
        self.tx_quantPArcelas.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_quantPArcelas.setObjectName("tx_quantPArcelas")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setGeometry(QtCore.QRect(620, 70, 151, 16))
        self.label_11.setObjectName("label_11")
        self.dt_vencimento = QtWidgets.QDateEdit(self.frame_11)
        self.dt_vencimento.setGeometry(QtCore.QRect(620, 90, 141, 31))
        self.dt_vencimento.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dt_vencimento.setStyleSheet("QDateEdit {\n"
"\n"
"    border: 2px solid lightgray;\n"
"    border-radius: 5px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
" \n"
"\n"
" \n"
"QDateEdit::drop-down:hover {\n"
"    /* Does this work with QDateEdit??? */\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d8d7d7, stop: 1 #e9e9e9);\n"
"}")
        self.dt_vencimento.setCalendarPopup(True)
        self.dt_vencimento.setObjectName("dt_vencimento")
        self.verticalLayout_5.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.wb_incluirParcelas)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_12.setStyleSheet("\n"
"QFrame{\n"
"border:none\n"
"}\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bt_SalvarPagamento = QtWidgets.QPushButton(self.frame_12)
        self.bt_SalvarPagamento.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.bt_SalvarPagamento.setFont(font)
        self.bt_SalvarPagamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_SalvarPagamento.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_SalvarPagamento.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_SalvarPagamento.setStyleSheet("")
        self.bt_SalvarPagamento.setIconSize(QtCore.QSize(75, 35))
        self.bt_SalvarPagamento.setObjectName("bt_SalvarPagamento")
        self.horizontalLayout_10.addWidget(self.bt_SalvarPagamento)
        self.bt_Altera = QtWidgets.QPushButton(self.frame_12)
        self.bt_Altera.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_Altera.setStyleSheet("")
        self.bt_Altera.setObjectName("bt_Altera")
        self.horizontalLayout_10.addWidget(self.bt_Altera)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.bt_sairlancamento = QtWidgets.QPushButton(self.frame_12)
        self.bt_sairlancamento.setMinimumSize(QtCore.QSize(0, 50))
        self.bt_sairlancamento.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:red;\n"
"padding:15px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        self.bt_sairlancamento.setObjectName("bt_sairlancamento")
        self.horizontalLayout_10.addWidget(self.bt_sairlancamento)
        self.verticalLayout_5.addWidget(self.frame_12)
        self.actioncaixa = QtWidgets.QAction(FormContaReceber)
        self.actioncaixa.setObjectName("actioncaixa")
        self.actionMARCA_TODAS_RECEBER = QtWidgets.QAction(FormContaReceber)
        self.actionMARCA_TODAS_RECEBER.setObjectName("actionMARCA_TODAS_RECEBER")
        self.actionDESMARCAR_TODAS = QtWidgets.QAction(FormContaReceber)
        self.actionDESMARCAR_TODAS.setObjectName("actionDESMARCAR_TODAS")

        self.retranslateUi(FormContaReceber)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(FormContaReceber)

    def retranslateUi(self, FormContaReceber):
        _translate = QtCore.QCoreApplication.translate
        FormContaReceber.setWindowTitle(_translate("FormContaReceber", "FormaContaReber"))
        self.label.setText(_translate("FormContaReceber", "contas a receber"))
        item = self.tb_geral.horizontalHeaderItem(0)
        item.setText(_translate("FormContaReceber", "ID"))
        item = self.tb_geral.horizontalHeaderItem(1)
        item.setText(_translate("FormContaReceber", "NOTA"))
        item = self.tb_geral.horizontalHeaderItem(2)
        item.setText(_translate("FormContaReceber", "documento"))
        item = self.tb_geral.horizontalHeaderItem(3)
        item.setText(_translate("FormContaReceber", "NOME CLIENTE"))
        item = self.tb_geral.horizontalHeaderItem(4)
        item.setText(_translate("FormContaReceber", "valor"))
        item = self.tb_geral.horizontalHeaderItem(5)
        item.setText(_translate("FormContaReceber", "parcelas"))
        item = self.tb_geral.horizontalHeaderItem(6)
        item.setText(_translate("FormContaReceber", "DATA EMISSAO"))
        item = self.tb_geral.horizontalHeaderItem(7)
        item.setText(_translate("FormContaReceber", "DATA VENCIMENTO"))
        item = self.tb_geral.horizontalHeaderItem(8)
        item.setText(_translate("FormContaReceber", "JUROS"))
        self.label_4.setText(_translate("FormContaReceber", "valor total"))
        self.valoGeral.setPrefix(_translate("FormContaReceber", "R$ "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.receber), _translate("FormContaReceber", "geral"))
        self.tx_buscarCliente.setPlaceholderText(_translate("FormContaReceber", "buscar cliente"))
        self.label_2.setText(_translate("FormContaReceber", "CODIGO"))
        self.label_3.setText(_translate("FormContaReceber", "NOME"))
        item = self.tab_receber.horizontalHeaderItem(0)
        item.setText(_translate("FormContaReceber", "S"))
        item = self.tab_receber.horizontalHeaderItem(1)
        item.setText(_translate("FormContaReceber", "ID"))
        item = self.tab_receber.horizontalHeaderItem(2)
        item.setText(_translate("FormContaReceber", "NOTA"))
        item = self.tab_receber.horizontalHeaderItem(3)
        item.setText(_translate("FormContaReceber", "documento"))
        item = self.tab_receber.horizontalHeaderItem(4)
        item.setText(_translate("FormContaReceber", "NOME CLIENTE"))
        item = self.tab_receber.horizontalHeaderItem(5)
        item.setText(_translate("FormContaReceber", "valor"))
        item = self.tab_receber.horizontalHeaderItem(6)
        item.setText(_translate("FormContaReceber", "parcelas"))
        item = self.tab_receber.horizontalHeaderItem(7)
        item.setText(_translate("FormContaReceber", "DATA EMISSAO"))
        item = self.tab_receber.horizontalHeaderItem(8)
        item.setText(_translate("FormContaReceber", "DATA VENCIMENTO"))
        item = self.tab_receber.horizontalHeaderItem(9)
        item.setText(_translate("FormContaReceber", "Dias Atraso"))
        self.bt_incluirReceber.setText(_translate("FormContaReceber", "incluir"))
        self.bt_AlteraREceber.setText(_translate("FormContaReceber", "altera"))
        self.bt_apagar.setText(_translate("FormContaReceber", "apagar"))
        self.bt_receber.setText(_translate("FormContaReceber", "baixa Notas"))
        self.bt_marcatodos.setText(_translate("FormContaReceber", "marca todos"))
        self.tx_valorTotalparcela.setPrefix(_translate("FormContaReceber", "TOTAL R$ "))
        self.tx_valorJuros.setPrefix(_translate("FormContaReceber", "juros R$ "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.receber1), _translate("FormContaReceber", "receber"))
        item = self.tab_recebidos.horizontalHeaderItem(0)
        item.setText(_translate("FormContaReceber", "NOTAS"))
        item = self.tab_recebidos.horizontalHeaderItem(1)
        item.setText(_translate("FormContaReceber", "DOCUMENTO"))
        item = self.tab_recebidos.horizontalHeaderItem(2)
        item.setText(_translate("FormContaReceber", "nome"))
        item = self.tab_recebidos.horizontalHeaderItem(3)
        item.setText(_translate("FormContaReceber", "VALOR nominal"))
        item = self.tab_recebidos.horizontalHeaderItem(4)
        item.setText(_translate("FormContaReceber", "DESCONTO"))
        item = self.tab_recebidos.horizontalHeaderItem(5)
        item.setText(_translate("FormContaReceber", "VALOR TOTAL"))
        item = self.tab_recebidos.horizontalHeaderItem(6)
        item.setText(_translate("FormContaReceber", "parcela"))
        item = self.tab_recebidos.horizontalHeaderItem(7)
        item.setText(_translate("FormContaReceber", "data emissao"))
        item = self.tab_recebidos.horizontalHeaderItem(8)
        item.setText(_translate("FormContaReceber", "data vencimento"))
        item = self.tab_recebidos.horizontalHeaderItem(9)
        item.setText(_translate("FormContaReceber", "data baixa"))
        self.bt_SalvarPagamento_2.setText(_translate("FormContaReceber", "estorna"))
        self.bt_SalvarPagamento_2.setShortcut(_translate("FormContaReceber", "F2"))
        self.db_Nominmal.setPrefix(_translate("FormContaReceber", "Nominal R$ "))
        self.tx_valorTotalparcela_2.setPrefix(_translate("FormContaReceber", "TOTAL R$ "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recebidos), _translate("FormContaReceber", "recebidos"))
        item = self.tb_atrasado.horizontalHeaderItem(0)
        item.setText(_translate("FormContaReceber", "ID"))
        item = self.tb_atrasado.horizontalHeaderItem(1)
        item.setText(_translate("FormContaReceber", "NOTA"))
        item = self.tb_atrasado.horizontalHeaderItem(2)
        item.setText(_translate("FormContaReceber", "documento"))
        item = self.tb_atrasado.horizontalHeaderItem(3)
        item.setText(_translate("FormContaReceber", "NOME CLIENTE"))
        item = self.tb_atrasado.horizontalHeaderItem(4)
        item.setText(_translate("FormContaReceber", "valor"))
        item = self.tb_atrasado.horizontalHeaderItem(5)
        item.setText(_translate("FormContaReceber", "parcelas"))
        item = self.tb_atrasado.horizontalHeaderItem(6)
        item.setText(_translate("FormContaReceber", "DATA EMISSAO"))
        item = self.tb_atrasado.horizontalHeaderItem(7)
        item.setText(_translate("FormContaReceber", "DATA VENCIMENTO"))
        item = self.tb_atrasado.horizontalHeaderItem(8)
        item.setText(_translate("FormContaReceber", "JUROS"))
        self.label_7.setText(_translate("FormContaReceber", "valor total"))
        self.db_atrasado.setPrefix(_translate("FormContaReceber", "R$ "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.atrasado), _translate("FormContaReceber", "atrasadas"))
        self.label_5.setText(_translate("FormContaReceber", "incluir parcelas"))
        self.label_6.setText(_translate("FormContaReceber", "codigo Cliente"))
        self.label_8.setText(_translate("FormContaReceber", "valor parcelas"))
        self.label_10.setText(_translate("FormContaReceber", "data de emissao"))
        self.label_12.setText(_translate("FormContaReceber", "nota"))
        self.label_9.setText(_translate("FormContaReceber", "nome cliente"))
        self.label_13.setText(_translate("FormContaReceber", "cod parcelas"))
        self.label_14.setText(_translate("FormContaReceber", "descriçao parcelas"))
        self.label_15.setText(_translate("FormContaReceber", "Quant Parcelas"))
        self.tx_quantPArcelas.setText(_translate("FormContaReceber", "0"))
        self.label_11.setText(_translate("FormContaReceber", "data de vencimento"))
        self.bt_SalvarPagamento.setText(_translate("FormContaReceber", "SALVAR (F2)"))
        self.bt_SalvarPagamento.setShortcut(_translate("FormContaReceber", "F2"))
        self.bt_Altera.setText(_translate("FormContaReceber", "alterar (F2)"))
        self.bt_Altera.setShortcut(_translate("FormContaReceber", "F2"))
        self.bt_sairlancamento.setText(_translate("FormContaReceber", "sair"))
        self.bt_sairlancamento.setShortcut(_translate("FormContaReceber", "Esc"))
        self.actioncaixa.setText(_translate("FormContaReceber", "BAIXA NOTA"))
        self.actionMARCA_TODAS_RECEBER.setText(_translate("FormContaReceber", "MARCA TODAS"))
        self.actionDESMARCAR_TODAS.setText(_translate("FormContaReceber", "DESMARCAR TODAS"))
