# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormIncluirTipodocumento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormIncluirTipodocumento(object):
    def setupUi(self, FormIncluirTipodocumento):
        FormIncluirTipodocumento.setObjectName("FormIncluirTipodocumento")
        FormIncluirTipodocumento.setWindowModality(QtCore.Qt.ApplicationModal)
        FormIncluirTipodocumento.resize(903, 717)
        FormIncluirTipodocumento.setStyleSheet("text-transform: uppercase;")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormIncluirTipodocumento)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(FormIncluirTipodocumento)
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(800, 700))
        self.widget.setStyleSheet("QWidget{\n"
"border:4px solid blue;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}\n"
"\n"
"QLabel{\n"
"text-transform: uppercase;\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.widget)
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"color:red;\n"
"border: none;\n"
"background-color:#2408D4;}\n"
"\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"border:none\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(500, 150))
        self.frame_4.setStyleSheet("QFrame{\n"
"background: #1E87F0;\n"
"border: 1px solid #1E87F0;\n"
"}\n"
"QLabel{\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none\n"
"}\n"
"QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"text-transform: uppercase;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);r\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.tx_codigo = QtWidgets.QLineEdit(self.frame_4)
        self.tx_codigo.setGeometry(QtCore.QRect(10, 30, 151, 41))
        self.tx_codigo.setMaxLength(3)
        self.tx_codigo.setObjectName("tx_codigo")
        self.tx_descricao = QtWidgets.QLineEdit(self.frame_4)
        self.tx_descricao.setGeometry(QtCore.QRect(180, 30, 391, 41))
        self.tx_descricao.setObjectName("tx_descricao")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 121, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.tab_Tipodocumento = QtWidgets.QTableWidget(self.frame_2)
        self.tab_Tipodocumento.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tab_Tipodocumento.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tab_Tipodocumento.setStyleSheet("QTableView{\n"
"color: black;\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"border:1px solid;\n"
"selection-color: rgb(0, 0, 255);\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"\n"
"font-size: 13px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border:none;\n"
"border-bottom: 2px solid black;\n"
"border-top:2px solid black;\n"
"padding:5px 0px;\n"
"text-transform: uppercase\n"
"}")
        self.tab_Tipodocumento.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_Tipodocumento.setTabKeyNavigation(False)
        self.tab_Tipodocumento.setProperty("showDropIndicator", False)
        self.tab_Tipodocumento.setDragDropOverwriteMode(False)
        self.tab_Tipodocumento.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab_Tipodocumento.setObjectName("tab_Tipodocumento")
        self.tab_Tipodocumento.setColumnCount(2)
        self.tab_Tipodocumento.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_Tipodocumento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_Tipodocumento.setHorizontalHeaderItem(1, item)
        self.tab_Tipodocumento.horizontalHeader().setSortIndicatorShown(False)
        self.tab_Tipodocumento.horizontalHeader().setStretchLastSection(True)
        self.tab_Tipodocumento.verticalHeader().setVisible(False)
        self.tab_Tipodocumento.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.tab_Tipodocumento)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setStyleSheet("border:none")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_incluir = QtWidgets.QPushButton(self.frame)
        self.bt_incluir.setMinimumSize(QtCore.QSize(0, 41))
        self.bt_incluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_incluir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_incluir.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF;\n"
"padding:5px 40px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_incluir.setObjectName("bt_incluir")
        self.horizontalLayout.addWidget(self.bt_incluir)
        self.bt_apagar = QtWidgets.QPushButton(self.frame)
        self.bt_apagar.setMinimumSize(QtCore.QSize(0, 41))
        self.bt_apagar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_apagar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_apagar.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF;\n"
"padding:10px 40px;\n"
"text-align:center;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_apagar.setObjectName("bt_apagar")
        self.horizontalLayout.addWidget(self.bt_apagar)
        self.bt_cancelaIcluir = QtWidgets.QPushButton(self.frame)
        self.bt_cancelaIcluir.setMinimumSize(QtCore.QSize(0, 41))
        self.bt_cancelaIcluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cancelaIcluir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelaIcluir.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF;\n"
"padding:5px 25px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_cancelaIcluir.setObjectName("bt_cancelaIcluir")
        self.horizontalLayout.addWidget(self.bt_cancelaIcluir)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_grava_altera = QtWidgets.QPushButton(self.frame)
        self.bt_grava_altera.setMinimumSize(QtCore.QSize(0, 41))
        self.bt_grava_altera.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_grava_altera.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bt_grava_altera.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF;\n"
"padding:5px 40px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_grava_altera.setObjectName("bt_grava_altera")
        self.horizontalLayout.addWidget(self.bt_grava_altera)
        self.bt_cancelar_Altera = QtWidgets.QPushButton(self.frame)
        self.bt_cancelar_Altera.setMinimumSize(QtCore.QSize(0, 41))
        self.bt_cancelar_Altera.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelar_Altera.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.bt_cancelar_Altera.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF;\n"
"padding:5px 40px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_cancelar_Altera.setObjectName("bt_cancelar_Altera")
        self.horizontalLayout.addWidget(self.bt_cancelar_Altera)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.widget_2)
        self.actionaltera_documento = QtWidgets.QAction(FormIncluirTipodocumento)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.actionaltera_documento.setFont(font)
        self.actionaltera_documento.setObjectName("actionaltera_documento")

        self.retranslateUi(FormIncluirTipodocumento)
        QtCore.QMetaObject.connectSlotsByName(FormIncluirTipodocumento)

    def retranslateUi(self, FormIncluirTipodocumento):
        _translate = QtCore.QCoreApplication.translate
        FormIncluirTipodocumento.setWindowTitle(_translate("FormIncluirTipodocumento", "Form"))
        self.label.setText(_translate("FormIncluirTipodocumento", "tipo documento"))
        self.tx_codigo.setPlaceholderText(_translate("FormIncluirTipodocumento", "codigo"))
        self.label_2.setText(_translate("FormIncluirTipodocumento", "codigo"))
        self.label_3.setText(_translate("FormIncluirTipodocumento", "descriçao"))
        item = self.tab_Tipodocumento.horizontalHeaderItem(0)
        item.setText(_translate("FormIncluirTipodocumento", "codigo"))
        item = self.tab_Tipodocumento.horizontalHeaderItem(1)
        item.setText(_translate("FormIncluirTipodocumento", "descriçao"))
        self.bt_incluir.setText(_translate("FormIncluirTipodocumento", "incluir"))
        self.bt_apagar.setText(_translate("FormIncluirTipodocumento", "apag ar"))
        self.bt_cancelaIcluir.setText(_translate("FormIncluirTipodocumento", "cancelar"))
        self.bt_cancelaIcluir.setShortcut(_translate("FormIncluirTipodocumento", "Esc"))
        self.bt_grava_altera.setText(_translate("FormIncluirTipodocumento", "gravar"))
        self.bt_cancelar_Altera.setText(_translate("FormIncluirTipodocumento", "cancelar"))
        self.actionaltera_documento.setText(_translate("FormIncluirTipodocumento", "altera documento"))
