# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormVisualisarNotasEntrada.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNotasEntrada(object):
    def setupUi(self, FormNotasEntrada):
        FormNotasEntrada.setObjectName("FormNotasEntrada")
        FormNotasEntrada.resize(1652, 725)
        FormNotasEntrada.setStyleSheet("\n"
"\n"
"QWidget#FormNotasEntrada{\n"
"text-transform: uppercase;\n"
"    background-color: rgb(85, 170, 255,150);\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(FormNotasEntrada)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(FormNotasEntrada)
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"    background-color: rgb(85, 170, 255,150);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMinimumSize(QtCore.QSize(1100, 0))
        self.widget.setMaximumSize(QtCore.QSize(1200, 800))
        self.widget.setStyleSheet("QWidget#widget{\n"
"text-transform: uppercase;\n"
"border:1px solid blue;\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.widget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"color:red;\n"
"border: none;\n"
"text-transform: uppercase;\n"
"background-color:#2408D4;}\n"
"\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"text-transform: uppercase;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("QFrame{\n"
"background: #1E87F0;\n"
"border: 1px solid #1E87F0;\n"
"}\n"
"QLabel{\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none\n"
"}\n"
"QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font-size: 16px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"text-transform: uppercase;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);r\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tx_BuscarNota = QtWidgets.QLineEdit(self.frame)
        self.tx_BuscarNota.setMinimumSize(QtCore.QSize(0, 50))
        self.tx_BuscarNota.setMaxLength(14)
        self.tx_BuscarNota.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_BuscarNota.setObjectName("tx_BuscarNota")
        self.horizontalLayout.addWidget(self.tx_BuscarNota)
        self.bt_BuscarNota = QtWidgets.QPushButton(self.frame)
        self.bt_BuscarNota.setMinimumSize(QtCore.QSize(100, 50))
        self.bt_BuscarNota.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_BuscarNota.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"font: 87 20pt \"Arial Black\";\n"
"border:none;")
        self.bt_BuscarNota.setObjectName("bt_BuscarNota")
        self.horizontalLayout.addWidget(self.bt_BuscarNota)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.tb_WidegNotas = QtWidgets.QTableWidget(self.widget)
        self.tb_WidegNotas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tb_WidegNotas.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tb_WidegNotas.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"text-transform: uppercase;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"text-transform: uppercase;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"  border: 0px solid black;\n"
"border-bottom:1px solid;\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"  background-color: blue;\n"
"  color: white;\n"
"}")
        self.tb_WidegNotas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_WidegNotas.setTabKeyNavigation(False)
        self.tb_WidegNotas.setProperty("showDropIndicator", False)
        self.tb_WidegNotas.setDragDropOverwriteMode(False)
        self.tb_WidegNotas.setAlternatingRowColors(True)
        self.tb_WidegNotas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_WidegNotas.setObjectName("tb_WidegNotas")
        self.tb_WidegNotas.setColumnCount(4)
        self.tb_WidegNotas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_WidegNotas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_WidegNotas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_WidegNotas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_WidegNotas.setHorizontalHeaderItem(3, item)
        self.tb_WidegNotas.horizontalHeader().setDefaultSectionSize(150)
        self.tb_WidegNotas.horizontalHeader().setStretchLastSection(True)
        self.tb_WidegNotas.verticalHeader().setVisible(False)
        self.tb_WidegNotas.verticalHeader().setDefaultSectionSize(48)
        self.verticalLayout.addWidget(self.tb_WidegNotas)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"color:red;\n"
"border: none;\n"
"text-transform: uppercase;\n"
"background-color:#2408D4;}\n"
"\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"text-transform: uppercase;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setStyleSheet("\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.tab_ProdutoVisualisar = QtWidgets.QTableWidget(self.frame_2)
        self.tab_ProdutoVisualisar.setMaximumSize(QtCore.QSize(16777215, 200))
        self.tab_ProdutoVisualisar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tab_ProdutoVisualisar.setStyleSheet("QTableWidget {\n"
"  background-color: white;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"text-transform: uppercase;\n"
"}\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"  background-color: gray;\n"
"  color: white;\n"
"  font-weight: bold;\n"
"text-transform: uppercase;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"  border: 0px solid black;\n"
"border-bottom:1px solid;\n"
"\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"  background-color: blue;\n"
"  color: white;\n"
"}")
        self.tab_ProdutoVisualisar.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_ProdutoVisualisar.setTabKeyNavigation(False)
        self.tab_ProdutoVisualisar.setProperty("showDropIndicator", False)
        self.tab_ProdutoVisualisar.setDragDropOverwriteMode(False)
        self.tab_ProdutoVisualisar.setAlternatingRowColors(True)
        self.tab_ProdutoVisualisar.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab_ProdutoVisualisar.setObjectName("tab_ProdutoVisualisar")
        self.tab_ProdutoVisualisar.setColumnCount(3)
        self.tab_ProdutoVisualisar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_ProdutoVisualisar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_ProdutoVisualisar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_ProdutoVisualisar.setHorizontalHeaderItem(2, item)
        self.tab_ProdutoVisualisar.horizontalHeader().setDefaultSectionSize(150)
        self.tab_ProdutoVisualisar.horizontalHeader().setStretchLastSection(True)
        self.tab_ProdutoVisualisar.verticalHeader().setVisible(False)
        self.tab_ProdutoVisualisar.verticalHeader().setDefaultSectionSize(48)
        self.verticalLayout_2.addWidget(self.tab_ProdutoVisualisar)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:red;\n"
"padding:15px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.bt_Sair = QtWidgets.QPushButton(self.frame_3)
        self.bt_Sair.setObjectName("bt_Sair")
        self.horizontalLayout_4.addWidget(self.bt_Sair)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.widget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.actionAPAGAR_NOTA = QtWidgets.QAction(FormNotasEntrada)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.actionAPAGAR_NOTA.setFont(font)
        self.actionAPAGAR_NOTA.setObjectName("actionAPAGAR_NOTA")
        self.actionEDITA_NOTA = QtWidgets.QAction(FormNotasEntrada)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.actionEDITA_NOTA.setFont(font)
        self.actionEDITA_NOTA.setObjectName("actionEDITA_NOTA")

        self.retranslateUi(FormNotasEntrada)
        QtCore.QMetaObject.connectSlotsByName(FormNotasEntrada)

    def retranslateUi(self, FormNotasEntrada):
        _translate = QtCore.QCoreApplication.translate
        FormNotasEntrada.setWindowTitle(_translate("FormNotasEntrada", "NOTAS"))
        self.label.setText(_translate("FormNotasEntrada", "NOTAS FISCAL"))
        self.tx_BuscarNota.setPlaceholderText(_translate("FormNotasEntrada", "numero nota"))
        self.bt_BuscarNota.setText(_translate("FormNotasEntrada", ">"))
        item = self.tb_WidegNotas.horizontalHeaderItem(0)
        item.setText(_translate("FormNotasEntrada", "id"))
        item = self.tb_WidegNotas.horizontalHeaderItem(1)
        item.setText(_translate("FormNotasEntrada", "nota"))
        item = self.tb_WidegNotas.horizontalHeaderItem(2)
        item.setText(_translate("FormNotasEntrada", "fornecedor"))
        item = self.tb_WidegNotas.horizontalHeaderItem(3)
        item.setText(_translate("FormNotasEntrada", "cnpj"))
        self.label_2.setText(_translate("FormNotasEntrada", "item notas"))
        item = self.tab_ProdutoVisualisar.horizontalHeaderItem(0)
        item.setText(_translate("FormNotasEntrada", "id"))
        item = self.tab_ProdutoVisualisar.horizontalHeaderItem(1)
        item.setText(_translate("FormNotasEntrada", "codigo barra"))
        item = self.tab_ProdutoVisualisar.horizontalHeaderItem(2)
        item.setText(_translate("FormNotasEntrada", "nome"))
        self.bt_Sair.setText(_translate("FormNotasEntrada", "SAIR"))
        self.actionAPAGAR_NOTA.setText(_translate("FormNotasEntrada", "APAGAR NOTA"))
        self.actionEDITA_NOTA.setText(_translate("FormNotasEntrada", "EDITA NOTA"))
