# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormIncluirEstoque.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Incluir_estoque(object):
    def setupUi(self, Form_Incluir_estoque):
        Form_Incluir_estoque.setObjectName("Form_Incluir_estoque")
        Form_Incluir_estoque.setWindowModality(QtCore.Qt.NonModal)
        Form_Incluir_estoque.setEnabled(True)
        Form_Incluir_estoque.resize(1294, 756)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/estoque.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_Incluir_estoque.setWindowIcon(icon)
        Form_Incluir_estoque.setStyleSheet("QWidget{\n"
"    background-color: rgb(85, 170, 255,150);\n"
"}")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form_Incluir_estoque)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(Form_Incluir_estoque)
        self.widget_2.setMinimumSize(QtCore.QSize(1200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"    \n"
"    background-color: rgb(0, 0, 0,200);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(1200, 800))
        self.widget.setStyleSheet("QWidget{\n"
"text-transform: uppercase;\n"
"border:1px solid blue;\n"
"    background-color: rgb(231, 231, 231);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr_TituloEsotuque = QtWidgets.QFrame(self.widget)
        self.fr_TituloEsotuque.setMinimumSize(QtCore.QSize(0, 40))
        self.fr_TituloEsotuque.setMaximumSize(QtCore.QSize(16777215, 40))
        self.fr_TituloEsotuque.setStyleSheet("\n"
"QFrame#fr_TituloEsotuque{\n"
"color:red;\n"
"border: none;\n"
"background-color:#2408D4;}\n"
"\n"
"QLabel{color: white;\n"
"background-color:transparent;\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"\n"
"}\n"
"")
        self.fr_TituloEsotuque.setObjectName("fr_TituloEsotuque")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_TituloEsotuque)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_TituloEstoque = QtWidgets.QLabel(self.fr_TituloEsotuque)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lb_TituloEstoque.setFont(font)
        self.lb_TituloEstoque.setStyleSheet("border:none")
        self.lb_TituloEstoque.setObjectName("lb_TituloEstoque")
        self.horizontalLayout.addWidget(self.lb_TituloEstoque)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.fr_TituloEsotuque)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 2px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"QWidget{\n"
"text-transform: uppercase;\n"
"border:0px solid blue;\n"
"background-color: rgb(231, 231, 231);\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"    background: #FFF;\n"
"boder:3px solid;\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(226, 226, 226);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"\n"
"text-transform: uppercase;\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: black;\n"
"    \n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"    background: #FFF;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.dadosproduto = QtWidgets.QWidget()
        self.dadosproduto.setStyleSheet("")
        self.dadosproduto.setObjectName("dadosproduto")
        self.label_16 = QtWidgets.QLabel(self.dadosproduto)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 51, 21))
        self.label_16.setObjectName("label_16")
        self.ch_codiBarra = QtWidgets.QCheckBox(self.dadosproduto)
        self.ch_codiBarra.setGeometry(QtCore.QRect(300, 30, 16, 20))
        self.ch_codiBarra.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ch_codiBarra.setStyleSheet("border:none;\n"
"background-color: transparent;")
        self.ch_codiBarra.setText("")
        self.ch_codiBarra.setObjectName("ch_codiBarra")
        self.tx_tipoDeUnidade = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_tipoDeUnidade.setGeometry(QtCore.QRect(830, 70, 71, 31))
        self.tx_tipoDeUnidade.setMaxLength(2)
        self.tx_tipoDeUnidade.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_tipoDeUnidade.setObjectName("tx_tipoDeUnidade")
        self.label_3 = QtWidgets.QLabel(self.dadosproduto)
        self.label_3.setGeometry(QtCore.QRect(770, 80, 61, 21))
        self.label_3.setObjectName("label_3")
        self.TX_IDpRODUTO = QtWidgets.QLineEdit(self.dadosproduto)
        self.TX_IDpRODUTO.setGeometry(QtCore.QRect(50, 30, 101, 31))
        self.TX_IDpRODUTO.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TX_IDpRODUTO.setAlignment(QtCore.Qt.AlignCenter)
        self.TX_IDpRODUTO.setObjectName("TX_IDpRODUTO")
        self.tx_Fornecedor = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_Fornecedor.setGeometry(QtCore.QRect(370, 120, 211, 31))
        self.tx_Fornecedor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_Fornecedor.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_Fornecedor.setObjectName("tx_Fornecedor")
        self.tx_MarcaProduto = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_MarcaProduto.setGeometry(QtCore.QRect(80, 120, 201, 31))
        self.tx_MarcaProduto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_MarcaProduto.setText("")
        self.tx_MarcaProduto.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_MarcaProduto.setObjectName("tx_MarcaProduto")
        self.tx_DescricaoGrupo = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_DescricaoGrupo.setGeometry(QtCore.QRect(690, 120, 191, 31))
        self.tx_DescricaoGrupo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_DescricaoGrupo.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_DescricaoGrupo.setObjectName("tx_DescricaoGrupo")
        self.tx_codGrupo = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_codGrupo.setGeometry(QtCore.QRect(600, 120, 91, 31))
        self.tx_codGrupo.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(231, 231, 231);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"\n"
"border:1px solid\n"
" }\n"
"QLineEdit:hover{\n"
"background-color: #40a286\n"
"}")
        self.tx_codGrupo.setText("")
        self.tx_codGrupo.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_codGrupo.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.tx_codGrupo.setObjectName("tx_codGrupo")
        self.label_8 = QtWidgets.QLabel(self.dadosproduto)
        self.label_8.setGeometry(QtCore.QRect(550, 240, 111, 21))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.tx_valorVenda = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.tx_valorVenda.setGeometry(QtCore.QRect(660, 240, 131, 31))
        self.tx_valorVenda.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_valorVenda.setStyleSheet("")
        self.tx_valorVenda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_valorVenda.setReadOnly(False)
        self.tx_valorVenda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_valorVenda.setProperty("showGroupSeparator", True)
        self.tx_valorVenda.setDecimals(3)
        self.tx_valorVenda.setMaximum(999999.0)
        self.tx_valorVenda.setSingleStep(1.0)
        self.tx_valorVenda.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.tx_valorVenda.setObjectName("tx_valorVenda")
        self.label = QtWidgets.QLabel(self.dadosproduto)
        self.label.setGeometry(QtCore.QRect(170, 30, 121, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dadosproduto)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_2.setObjectName("label_2")
        self.tx_DescricaoProduto = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_DescricaoProduto.setGeometry(QtCore.QRect(100, 70, 661, 31))
        self.tx_DescricaoProduto.setStyleSheet("")
        self.tx_DescricaoProduto.setObjectName("tx_DescricaoProduto")
        self.tx_codigoBarra = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_codigoBarra.setGeometry(QtCore.QRect(330, 30, 131, 31))
        self.tx_codigoBarra.setMaxLength(15)
        self.tx_codigoBarra.setObjectName("tx_codigoBarra")
        self.label_9 = QtWidgets.QLabel(self.dadosproduto)
        self.label_9.setGeometry(QtCore.QRect(270, 200, 133, 18))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.db_compra = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.db_compra.setGeometry(QtCore.QRect(410, 190, 133, 29))
        self.db_compra.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.db_compra.setWrapping(False)
        self.db_compra.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_compra.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_compra.setProperty("showGroupSeparator", True)
        self.db_compra.setMaximum(99999.0)
        self.db_compra.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.db_compra.setObjectName("db_compra")
        self.label_10 = QtWidgets.QLabel(self.dadosproduto)
        self.label_10.setGeometry(QtCore.QRect(270, 230, 133, 18))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.db_custo = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.db_custo.setGeometry(QtCore.QRect(410, 230, 133, 29))
        self.db_custo.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.db_custo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_custo.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_custo.setProperty("showGroupSeparator", True)
        self.db_custo.setMaximum(99999.0)
        self.db_custo.setObjectName("db_custo")
        self.label_11 = QtWidgets.QLabel(self.dadosproduto)
        self.label_11.setGeometry(QtCore.QRect(270, 270, 121, 18))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.db_lucro = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.db_lucro.setGeometry(QtCore.QRect(410, 270, 133, 29))
        self.db_lucro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_lucro.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_lucro.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_lucro.setProperty("showGroupSeparator", True)
        self.db_lucro.setMaximum(99999.0)
        self.db_lucro.setObjectName("db_lucro")
        self.label_6 = QtWidgets.QLabel(self.dadosproduto)
        self.label_6.setGeometry(QtCore.QRect(0, 200, 143, 14))
        self.label_6.setObjectName("label_6")
        self.tx_QuantidadeProduto = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.tx_QuantidadeProduto.setGeometry(QtCore.QRect(110, 190, 143, 29))
        self.tx_QuantidadeProduto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_QuantidadeProduto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_QuantidadeProduto.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_QuantidadeProduto.setProperty("showGroupSeparator", True)
        self.tx_QuantidadeProduto.setMaximum(99999.0)
        self.tx_QuantidadeProduto.setObjectName("tx_QuantidadeProduto")
        self.label_13 = QtWidgets.QLabel(self.dadosproduto)
        self.label_13.setGeometry(QtCore.QRect(0, 240, 121, 16))
        self.label_13.setObjectName("label_13")
        self.tx_maximoproduto = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_maximoproduto.setGeometry(QtCore.QRect(110, 230, 143, 24))
        self.tx_maximoproduto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_maximoproduto.setObjectName("tx_maximoproduto")
        self.label_14 = QtWidgets.QLabel(self.dadosproduto)
        self.label_14.setGeometry(QtCore.QRect(0, 280, 143, 14))
        self.label_14.setObjectName("label_14")
        self.tx_minimoProduto = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_minimoProduto.setGeometry(QtCore.QRect(110, 270, 143, 24))
        self.tx_minimoProduto.setMaxLength(10)
        self.tx_minimoProduto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_minimoProduto.setObjectName("tx_minimoProduto")
        self.tx_codfornecedo = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_codfornecedo.setGeometry(QtCore.QRect(300, 120, 71, 31))
        self.tx_codfornecedo.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(231, 231, 231);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"\n"
"border:1px solid\n"
" }\n"
"QLineEdit:hover{\n"
"background-color: #40a286\n"
"}")
        self.tx_codfornecedo.setText("")
        self.tx_codfornecedo.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_codfornecedo.setObjectName("tx_codfornecedo")
        self.tx_codmarca = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_codmarca.setGeometry(QtCore.QRect(10, 120, 71, 31))
        self.tx_codmarca.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(231, 231, 231);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"\n"
"border:1px solid\n"
" }\n"
"QLineEdit:hover{\n"
"background-color: #40a286\n"
"}")
        self.tx_codmarca.setText("")
        self.tx_codmarca.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_codmarca.setObjectName("tx_codmarca")
        self.groupBox = QtWidgets.QGroupBox(self.dadosproduto)
        self.groupBox.setGeometry(QtCore.QRect(940, 210, 211, 281))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"\n"
"  border: 1px solid #ccc;\n"
"  padding: 10px;\n"
"  margin-bottom: 10px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cheativo = QtWidgets.QCheckBox(self.groupBox)
        self.cheativo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cheativo.setChecked(True)
        self.cheativo.setObjectName("cheativo")
        self.verticalLayout_2.addWidget(self.cheativo)
        self.chefotos = QtWidgets.QCheckBox(self.groupBox)
        self.chefotos.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.chefotos.setTristate(True)
        self.chefotos.setObjectName("chefotos")
        self.verticalLayout_2.addWidget(self.chefotos)
        self.chetributos = QtWidgets.QCheckBox(self.groupBox)
        self.chetributos.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.chetributos.setTristate(True)
        self.chetributos.setObjectName("chetributos")
        self.verticalLayout_2.addWidget(self.chetributos)
        self.chehistorico = QtWidgets.QCheckBox(self.groupBox)
        self.chehistorico.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.chehistorico.setTristate(True)
        self.chehistorico.setObjectName("chehistorico")
        self.verticalLayout_2.addWidget(self.chehistorico)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_20 = QtWidgets.QLabel(self.dadosproduto)
        self.label_20.setGeometry(QtCore.QRect(260, 310, 121, 18))
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.db_lucroreal = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.db_lucroreal.setGeometry(QtCore.QRect(410, 310, 133, 29))
        self.db_lucroreal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_lucroreal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_lucroreal.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_lucroreal.setProperty("showGroupSeparator", True)
        self.db_lucroreal.setMaximum(99999.0)
        self.db_lucroreal.setObjectName("db_lucroreal")
        self.label_21 = QtWidgets.QLabel(self.dadosproduto)
        self.label_21.setGeometry(QtCore.QRect(550, 190, 111, 21))
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.tx_porcentagemvenda = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.tx_porcentagemvenda.setGeometry(QtCore.QRect(660, 190, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tx_porcentagemvenda.setFont(font)
        self.tx_porcentagemvenda.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_porcentagemvenda.setStyleSheet("")
        self.tx_porcentagemvenda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_porcentagemvenda.setReadOnly(False)
        self.tx_porcentagemvenda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_porcentagemvenda.setProperty("showGroupSeparator", True)
        self.tx_porcentagemvenda.setDecimals(3)
        self.tx_porcentagemvenda.setMaximum(999999.0)
        self.tx_porcentagemvenda.setSingleStep(1.0)
        self.tx_porcentagemvenda.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.tx_porcentagemvenda.setObjectName("tx_porcentagemvenda")
        self.label_15 = QtWidgets.QLabel(self.dadosproduto)
        self.label_15.setGeometry(QtCore.QRect(0, 340, 81, 16))
        self.label_15.setObjectName("label_15")
        self.tx_ncm = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_ncm.setGeometry(QtCore.QRect(110, 340, 143, 24))
        self.tx_ncm.setMaxLength(8)
        self.tx_ncm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_ncm.setObjectName("tx_ncm")
        self.tx_fracaoPRoduto = QtWidgets.QLineEdit(self.dadosproduto)
        self.tx_fracaoPRoduto.setGeometry(QtCore.QRect(110, 380, 143, 24))
        self.tx_fracaoPRoduto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_fracaoPRoduto.setMaxLength(2)
        self.tx_fracaoPRoduto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tx_fracaoPRoduto.setPlaceholderText("")
        self.tx_fracaoPRoduto.setObjectName("tx_fracaoPRoduto")
        self.label_7 = QtWidgets.QLabel(self.dadosproduto)
        self.label_7.setGeometry(QtCore.QRect(0, 380, 81, 16))
        self.label_7.setObjectName("label_7")
        self.db_pisCusto = QtWidgets.QDoubleSpinBox(self.dadosproduto)
        self.db_pisCusto.setGeometry(QtCore.QRect(110, 420, 141, 31))
        self.db_pisCusto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.db_pisCusto.setWrapping(False)
        self.db_pisCusto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_pisCusto.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_pisCusto.setProperty("showGroupSeparator", True)
        self.db_pisCusto.setPrefix("")
        self.db_pisCusto.setMaximum(99999.0)
        self.db_pisCusto.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.db_pisCusto.setObjectName("db_pisCusto")
        self.label_12 = QtWidgets.QLabel(self.dadosproduto)
        self.label_12.setGeometry(QtCore.QRect(0, 430, 101, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lb_codigoBarra = QtWidgets.QLabel(self.dadosproduto)
        self.lb_codigoBarra.setGeometry(QtCore.QRect(950, 10, 181, 131))
        self.lb_codigoBarra.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border:none;")
        self.lb_codigoBarra.setText("")
        self.lb_codigoBarra.setScaledContents(True)
        self.lb_codigoBarra.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_codigoBarra.setObjectName("lb_codigoBarra")
        self.label.raise_()
        self.label_16.raise_()
        self.ch_codiBarra.raise_()
        self.tx_tipoDeUnidade.raise_()
        self.label_3.raise_()
        self.TX_IDpRODUTO.raise_()
        self.tx_Fornecedor.raise_()
        self.tx_MarcaProduto.raise_()
        self.tx_DescricaoGrupo.raise_()
        self.tx_codGrupo.raise_()
        self.label_8.raise_()
        self.tx_valorVenda.raise_()
        self.label_2.raise_()
        self.tx_DescricaoProduto.raise_()
        self.tx_codigoBarra.raise_()
        self.label_9.raise_()
        self.db_compra.raise_()
        self.label_10.raise_()
        self.db_custo.raise_()
        self.label_11.raise_()
        self.db_lucro.raise_()
        self.label_6.raise_()
        self.tx_QuantidadeProduto.raise_()
        self.label_13.raise_()
        self.tx_maximoproduto.raise_()
        self.label_14.raise_()
        self.tx_minimoProduto.raise_()
        self.tx_codfornecedo.raise_()
        self.tx_codmarca.raise_()
        self.groupBox.raise_()
        self.label_20.raise_()
        self.db_lucroreal.raise_()
        self.label_21.raise_()
        self.tx_porcentagemvenda.raise_()
        self.label_15.raise_()
        self.tx_ncm.raise_()
        self.tx_fracaoPRoduto.raise_()
        self.label_7.raise_()
        self.db_pisCusto.raise_()
        self.label_12.raise_()
        self.lb_codigoBarra.raise_()
        self.tabWidget.addTab(self.dadosproduto, "")
        self.tributos = QtWidgets.QWidget()
        self.tributos.setObjectName("tributos")
        self.label_17 = QtWidgets.QLabel(self.tributos)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.label_17.setObjectName("label_17")
        self.tx_cfopSaida = QtWidgets.QLineEdit(self.tributos)
        self.tx_cfopSaida.setGeometry(QtCore.QRect(110, 90, 101, 21))
        self.tx_cfopSaida.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_cfopSaida.setMaxLength(4)
        self.tx_cfopSaida.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_cfopSaida.setObjectName("tx_cfopSaida")
        self.tx_CstSaida = QtWidgets.QLineEdit(self.tributos)
        self.tx_CstSaida.setGeometry(QtCore.QRect(110, 120, 101, 21))
        self.tx_CstSaida.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_CstSaida.setText("")
        self.tx_CstSaida.setMaxLength(4)
        self.tx_CstSaida.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_CstSaida.setObjectName("tx_CstSaida")
        self.cb_classificacao = QtWidgets.QComboBox(self.tributos)
        self.cb_classificacao.setGeometry(QtCore.QRect(40, 30, 231, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cb_classificacao.setFont(font)
        self.cb_classificacao.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.cb_classificacao.setObjectName("cb_classificacao")
        self.cb_classificacao.addItem("")
        self.cb_classificacao.setItemText(0, "")
        self.label_18 = QtWidgets.QLabel(self.tributos)
        self.label_18.setGeometry(QtCore.QRect(40, 10, 211, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tributos)
        self.label_19.setGeometry(QtCore.QRect(10, 120, 101, 20))
        self.label_19.setObjectName("label_19")
        self.tx_codst = QtWidgets.QLineEdit(self.tributos)
        self.tx_codst.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.tx_codst.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_codst.setMaxLength(1)
        self.tx_codst.setObjectName("tx_codst")
        self.tabWidget.addTab(self.tributos, "")
        self.fotos = QtWidgets.QWidget()
        self.fotos.setObjectName("fotos")
        self.lb_fotos_estoque = QtWidgets.QLabel(self.fotos)
        self.lb_fotos_estoque.setGeometry(QtCore.QRect(20, 10, 551, 411))
        self.lb_fotos_estoque.setStyleSheet("background-color:#538fff;")
        self.lb_fotos_estoque.setText("")
        self.lb_fotos_estoque.setPixmap(QtGui.QPixmap(":/newPrefix/img/profile.png"))
        self.lb_fotos_estoque.setScaledContents(True)
        self.lb_fotos_estoque.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_fotos_estoque.setObjectName("lb_fotos_estoque")
        self.bt_selecionar_foto = QtWidgets.QPushButton(self.fotos)
        self.bt_selecionar_foto.setGeometry(QtCore.QRect(40, 360, 41, 41))
        self.bt_selecionar_foto.setMinimumSize(QtCore.QSize(35, 35))
        self.bt_selecionar_foto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_selecionar_foto.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_selecionar_foto.setStyleSheet("QPushButton{\n"
"\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:20px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"background-color: #7AB32E;\n"
"    margin:0px\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/img/mais.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_selecionar_foto.setIcon(icon1)
        self.bt_selecionar_foto.setIconSize(QtCore.QSize(30, 30))
        self.bt_selecionar_foto.setObjectName("bt_selecionar_foto")
        self.tabWidget.addTab(self.fotos, "")
        self.HISTORICO = QtWidgets.QWidget()
        self.HISTORICO.setObjectName("HISTORICO")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.HISTORICO)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lb_FormProdutos_9 = QtWidgets.QLabel(self.HISTORICO)
        self.lb_FormProdutos_9.setStyleSheet("")
        self.lb_FormProdutos_9.setObjectName("lb_FormProdutos_9")
        self.verticalLayout_7.addWidget(self.lb_FormProdutos_9)
        self.tb_HistoricoComprasProduto = QtWidgets.QTableWidget(self.HISTORICO)
        self.tb_HistoricoComprasProduto.setStyleSheet("QTableView{\n"
"background: #F1F1F1;\n"
"color: black;\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"border:1px solid;\n"
"    selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 170, 255);\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"\n"
"font-size: 13px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border:none;\n"
"border-bottom: 2px solid black;\n"
"border-top:2px solid black;\n"
"padding:5px 0px;\n"
"text-transform: uppercase\n"
"}")
        self.tb_HistoricoComprasProduto.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tb_HistoricoComprasProduto.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tb_HistoricoComprasProduto.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_HistoricoComprasProduto.setTabKeyNavigation(False)
        self.tb_HistoricoComprasProduto.setAlternatingRowColors(True)
        self.tb_HistoricoComprasProduto.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_HistoricoComprasProduto.setShowGrid(False)
        self.tb_HistoricoComprasProduto.setObjectName("tb_HistoricoComprasProduto")
        self.tb_HistoricoComprasProduto.setColumnCount(3)
        self.tb_HistoricoComprasProduto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tb_HistoricoComprasProduto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tb_HistoricoComprasProduto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tb_HistoricoComprasProduto.setHorizontalHeaderItem(2, item)
        self.tb_HistoricoComprasProduto.horizontalHeader().setDefaultSectionSize(140)
        self.tb_HistoricoComprasProduto.verticalHeader().setVisible(False)
        self.tb_HistoricoComprasProduto.verticalHeader().setHighlightSections(False)
        self.verticalLayout_7.addWidget(self.tb_HistoricoComprasProduto)
        self.lb_FormProdutos_8 = QtWidgets.QLabel(self.HISTORICO)
        self.lb_FormProdutos_8.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormProdutos_8.setObjectName("lb_FormProdutos_8")
        self.verticalLayout_7.addWidget(self.lb_FormProdutos_8)
        self.tx_ObsProduto = QtWidgets.QTextEdit(self.HISTORICO)
        self.tx_ObsProduto.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tx_ObsProduto.setStyleSheet("border:0px;\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;")
        self.tx_ObsProduto.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tx_ObsProduto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tx_ObsProduto.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.tx_ObsProduto.setObjectName("tx_ObsProduto")
        self.verticalLayout_7.addWidget(self.tx_ObsProduto)
        self.tabWidget.addTab(self.HISTORICO, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame)
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(self.widget)
        self.fr_BotoesFormProdutos.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fr_BotoesFormProdutos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fr_BotoesFormProdutos)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.bt_Salvar = QtWidgets.QPushButton(self.fr_BotoesFormProdutos)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_Salvar.setFont(font)
        self.bt_Salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_Salvar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_Salvar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_Salvar.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF;\n"
"padding:15px 60px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_Salvar.setIconSize(QtCore.QSize(75, 35))
        self.bt_Salvar.setObjectName("bt_Salvar")
        self.horizontalLayout_2.addWidget(self.bt_Salvar)
        self.bt_clostela = QtWidgets.QPushButton(self.fr_BotoesFormProdutos)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bt_clostela.setFont(font)
        self.bt_clostela.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_clostela.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_clostela.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.bt_clostela.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF;\n"
"padding:15px 60px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_clostela.setIconSize(QtCore.QSize(75, 35))
        self.bt_clostela.setObjectName("bt_clostela")
        self.horizontalLayout_2.addWidget(self.bt_clostela)
        self.verticalLayout.addWidget(self.fr_BotoesFormProdutos)
        self.horizontalLayout_4.addWidget(self.widget)
        self.horizontalLayout_3.addWidget(self.widget_2)

        self.retranslateUi(Form_Incluir_estoque)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_Incluir_estoque)
        Form_Incluir_estoque.setTabOrder(self.tx_codigoBarra, self.tx_DescricaoProduto)
        Form_Incluir_estoque.setTabOrder(self.tx_DescricaoProduto, self.tx_tipoDeUnidade)
        Form_Incluir_estoque.setTabOrder(self.tx_tipoDeUnidade, self.tx_codmarca)
        Form_Incluir_estoque.setTabOrder(self.tx_codmarca, self.tx_codfornecedo)
        Form_Incluir_estoque.setTabOrder(self.tx_codfornecedo, self.tx_codGrupo)
        Form_Incluir_estoque.setTabOrder(self.tx_codGrupo, self.tx_QuantidadeProduto)
        Form_Incluir_estoque.setTabOrder(self.tx_QuantidadeProduto, self.tx_maximoproduto)
        Form_Incluir_estoque.setTabOrder(self.tx_maximoproduto, self.tx_minimoProduto)
        Form_Incluir_estoque.setTabOrder(self.tx_minimoProduto, self.db_compra)
        Form_Incluir_estoque.setTabOrder(self.db_compra, self.db_custo)
        Form_Incluir_estoque.setTabOrder(self.db_custo, self.tx_porcentagemvenda)
        Form_Incluir_estoque.setTabOrder(self.tx_porcentagemvenda, self.tx_valorVenda)
        Form_Incluir_estoque.setTabOrder(self.tx_valorVenda, self.tx_cfopSaida)
        Form_Incluir_estoque.setTabOrder(self.tx_cfopSaida, self.tx_CstSaida)
        Form_Incluir_estoque.setTabOrder(self.tx_CstSaida, self.tb_HistoricoComprasProduto)
        Form_Incluir_estoque.setTabOrder(self.tb_HistoricoComprasProduto, self.cb_classificacao)

    def retranslateUi(self, Form_Incluir_estoque):
        _translate = QtCore.QCoreApplication.translate
        Form_Incluir_estoque.setWindowTitle(_translate("Form_Incluir_estoque", "Cadastro Estoque"))
        self.lb_TituloEstoque.setText(_translate("Form_Incluir_estoque", "cadastro estoque"))
        self.label_16.setText(_translate("Form_Incluir_estoque", "ID"))
        self.ch_codiBarra.setToolTip(_translate("Form_Incluir_estoque", "gera codigo barra"))
        self.tx_tipoDeUnidade.setText(_translate("Form_Incluir_estoque", "un"))
        self.tx_tipoDeUnidade.setPlaceholderText(_translate("Form_Incluir_estoque", "unidade"))
        self.label_3.setText(_translate("Form_Incluir_estoque", "unidade"))
        self.TX_IDpRODUTO.setPlaceholderText(_translate("Form_Incluir_estoque", "id"))
        self.tx_Fornecedor.setPlaceholderText(_translate("Form_Incluir_estoque", "fornecedor"))
        self.tx_MarcaProduto.setPlaceholderText(_translate("Form_Incluir_estoque", "marca"))
        self.tx_DescricaoGrupo.setPlaceholderText(_translate("Form_Incluir_estoque", "grupo"))
        self.tx_codGrupo.setPlaceholderText(_translate("Form_Incluir_estoque", "codproduto"))
        self.label_8.setText(_translate("Form_Incluir_estoque", "valor de venda"))
        self.tx_valorVenda.setPrefix(_translate("Form_Incluir_estoque", "R$ "))
        self.label.setText(_translate("Form_Incluir_estoque", "CODIGO BARRA"))
        self.label_2.setText(_translate("Form_Incluir_estoque", "Descriçao*"))
        self.tx_DescricaoProduto.setPlaceholderText(_translate("Form_Incluir_estoque", "descriçao produto"))
        self.tx_codigoBarra.setPlaceholderText(_translate("Form_Incluir_estoque", "codigo barra"))
        self.label_9.setText(_translate("Form_Incluir_estoque", "preço compra"))
        self.db_compra.setPrefix(_translate("Form_Incluir_estoque", "R$ "))
        self.label_10.setText(_translate("Form_Incluir_estoque", "preço custo"))
        self.db_custo.setPrefix(_translate("Form_Incluir_estoque", "R$ "))
        self.label_11.setText(_translate("Form_Incluir_estoque", "lucro(%)"))
        self.db_lucro.setPrefix(_translate("Form_Incluir_estoque", "% "))
        self.label_6.setText(_translate("Form_Incluir_estoque", "quant produto"))
        self.label_13.setText(_translate("Form_Incluir_estoque", "max produto"))
        self.label_14.setText(_translate("Form_Incluir_estoque", "min produto"))
        self.tx_codfornecedo.setPlaceholderText(_translate("Form_Incluir_estoque", "codfor"))
        self.tx_codmarca.setPlaceholderText(_translate("Form_Incluir_estoque", "codmarc"))
        self.groupBox.setTitle(_translate("Form_Incluir_estoque", "paramentro"))
        self.cheativo.setText(_translate("Form_Incluir_estoque", "ativo"))
        self.chefotos.setText(_translate("Form_Incluir_estoque", "fotos"))
        self.chetributos.setText(_translate("Form_Incluir_estoque", "tributos"))
        self.chehistorico.setText(_translate("Form_Incluir_estoque", "historico"))
        self.label_20.setText(_translate("Form_Incluir_estoque", "lucro real"))
        self.db_lucroreal.setPrefix(_translate("Form_Incluir_estoque", "R$ "))
        self.label_21.setText(_translate("Form_Incluir_estoque", "porc% venda"))
        self.tx_porcentagemvenda.setPrefix(_translate("Form_Incluir_estoque", "R$ "))
        self.label_15.setText(_translate("Form_Incluir_estoque", "NCM*"))
        self.tx_fracaoPRoduto.setText(_translate("Form_Incluir_estoque", "1"))
        self.label_7.setText(_translate("Form_Incluir_estoque", "Fraçao"))
        self.label_12.setText(_translate("Form_Incluir_estoque", "calculo pis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dadosproduto), _translate("Form_Incluir_estoque", "dados produto"))
        self.label_17.setText(_translate("Form_Incluir_estoque", "cfop saida"))
        self.label_18.setText(_translate("Form_Incluir_estoque", "*classificaçao fiscal"))
        self.label_19.setText(_translate("Form_Incluir_estoque", "cst saida"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tributos), _translate("Form_Incluir_estoque", "TRIBUTOS"))
        self.bt_selecionar_foto.setToolTip(_translate("Form_Incluir_estoque", "Selecionar Foto"))
        self.bt_selecionar_foto.setText(_translate("Form_Incluir_estoque", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fotos), _translate("Form_Incluir_estoque", "fotos"))
        self.lb_FormProdutos_9.setText(_translate("Form_Incluir_estoque", "HISTÓRICO DE COMPRAS"))
        item = self.tb_HistoricoComprasProduto.horizontalHeaderItem(0)
        item.setText(_translate("Form_Incluir_estoque", "DATA"))
        item = self.tb_HistoricoComprasProduto.horizontalHeaderItem(1)
        item.setText(_translate("Form_Incluir_estoque", "QTDE"))
        item = self.tb_HistoricoComprasProduto.horizontalHeaderItem(2)
        item.setText(_translate("Form_Incluir_estoque", "VALOR"))
        self.lb_FormProdutos_8.setText(_translate("Form_Incluir_estoque", "OBSERVAÇÃO"))
        self.tx_ObsProduto.setDocumentTitle(_translate("Form_Incluir_estoque", "OBS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HISTORICO), _translate("Form_Incluir_estoque", "HISTORICO"))
        self.bt_Salvar.setText(_translate("Form_Incluir_estoque", "SALVAR (F2)"))
        self.bt_Salvar.setShortcut(_translate("Form_Incluir_estoque", "F2"))
        self.bt_clostela.setText(_translate("Form_Incluir_estoque", "VOLTAR"))
        self.bt_clostela.setShortcut(_translate("Form_Incluir_estoque", "Esc"))
