# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormRestaurante.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formrestaurante(object):
    def setupUi(self, Formrestaurante):
        Formrestaurante.setObjectName("Formrestaurante")
        Formrestaurante.setWindowModality(QtCore.Qt.ApplicationModal)
        Formrestaurante.resize(1533, 882)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/restauranteICONE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Formrestaurante.setWindowIcon(icon)
        Formrestaurante.setStyleSheet("border:none;\n"
"text-transform: uppercase;\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Formrestaurante)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fundo = QtWidgets.QWidget(Formrestaurante)
        self.fundo.setObjectName("fundo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fundo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.fundo)
        self.widget.setStyleSheet("background-color: none;")
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 1, 1, 2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fr_TituloClientes = QtWidgets.QFrame(self.widget)
        self.fr_TituloClientes.setMinimumSize(QtCore.QSize(0, 45))
        self.fr_TituloClientes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fr_TituloClientes.setStyleSheet("QFrame#fr_TituloClientes{\n"
"color:red;\n"
"border: none;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(0, 0, 255, 212), stop:1 rgba(255, 255, 255, 255));}\n"
"\n"
"QToolButton { /* all types of tool button */\n"
"      padding:5px 25px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 14pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(0, 0, 255, 91), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QToolButton::menu-arrow {\n"
"   \n"
"    image: url(:/seta/icons/arrow_down.gif);\n"
"}\n"
"")
        self.fr_TituloClientes.setObjectName("fr_TituloClientes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_TituloClientes)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.toolButton = QtWidgets.QToolButton(self.fr_TituloClientes)
        self.toolButton.setMinimumSize(QtCore.QSize(120, 0))
        self.toolButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/caixabranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(40, 35))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_3.addWidget(self.toolButton)
        self.bt_criamesa = QtWidgets.QToolButton(self.fr_TituloClientes)
        self.bt_criamesa.setMinimumSize(QtCore.QSize(120, 0))
        self.bt_criamesa.setSizeIncrement(QtCore.QSize(120, 0))
        self.bt_criamesa.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/MESABRANCA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_criamesa.setIcon(icon2)
        self.bt_criamesa.setIconSize(QtCore.QSize(40, 35))
        self.bt_criamesa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_criamesa.setObjectName("bt_criamesa")
        self.horizontalLayout_3.addWidget(self.bt_criamesa)
        self.bt_fechamesa = QtWidgets.QToolButton(self.fr_TituloClientes)
        self.bt_fechamesa.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/apagabranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_fechamesa.setIcon(icon3)
        self.bt_fechamesa.setIconSize(QtCore.QSize(40, 35))
        self.bt_fechamesa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_fechamesa.setObjectName("bt_fechamesa")
        self.horizontalLayout_3.addWidget(self.bt_fechamesa)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.toolButton_4 = QtWidgets.QToolButton(self.fr_TituloClientes)
        self.toolButton_4.setMinimumSize(QtCore.QSize(120, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/entregabranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setIconSize(QtCore.QSize(40, 35))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_3.addWidget(self.toolButton_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.fr_TituloClientes)
        self.toolButton_3.setMinimumSize(QtCore.QSize(120, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/setabaixo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon5)
        self.toolButton_3.setIconSize(QtCore.QSize(40, 35))
        self.toolButton_3.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_3.addWidget(self.toolButton_3)
        self.verticalLayout_5.addWidget(self.fr_TituloClientes)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"text-transform: uppercase;\n"
"border:1px solid blue;\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_3.setStyleSheet("QWidget#widget_3{\n"
"text-transform: uppercase;\n"
"\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.widget_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 0 8px;\n"
"    background-color: rgb(229, 229, 229);\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(120, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(120, 60, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.spin_mesa = QtWidgets.QSpinBox(self.frame)
        self.spin_mesa.setEnabled(False)
        self.spin_mesa.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.spin_mesa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spin_mesa.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 0 8px;\n"
"background-color: rgb(255, 255, 255);")
        self.spin_mesa.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_mesa.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_mesa.setSpecialValueText("")
        self.spin_mesa.setMaximum(1200)
        self.spin_mesa.setObjectName("spin_mesa")
        self.spin_garcon = QtWidgets.QSpinBox(self.frame)
        self.spin_garcon.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.spin_garcon.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 0 8px;\n"
"background-color: rgb(255, 255, 255);")
        self.spin_garcon.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_garcon.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_garcon.setSpecialValueText("")
        self.spin_garcon.setMaximum(1200)
        self.spin_garcon.setObjectName("spin_garcon")
        self.data = QtWidgets.QLabel(self.frame)
        self.data.setGeometry(QtCore.QRect(310, 10, 121, 31))
        self.data.setText("")
        self.data.setAlignment(QtCore.Qt.AlignCenter)
        self.data.setObjectName("data")
        self.bt_finalizaVenda = QtWidgets.QPushButton(self.frame)
        self.bt_finalizaVenda.setGeometry(QtCore.QRect(10, 100, 141, 24))
        self.bt_finalizaVenda.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_finalizaVenda.setObjectName("bt_finalizaVenda")
        self.bt_delete = QtWidgets.QPushButton(self.frame)
        self.bt_delete.setGeometry(QtCore.QRect(150, 100, 141, 24))
        self.bt_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_delete.setObjectName("bt_delete")
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.widget_3)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_5.setStyleSheet("QFrame{\n"
"color:red;\n"
"border: none;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(0, 0, 255, 212), stop:1 rgba(255, 255, 255, 255));}\n"
"QLineEdit {\n"
"    border: 2px solid gray;\n"
"    font: 14pt \"Segoe UI\";\n"
"    padding: 0 8px;\n"
"    background-color: rgb(229, 229, 229);\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.bt_adicionarproduto = QtWidgets.QPushButton(self.frame_5)
        self.bt_adicionarproduto.setGeometry(QtCore.QRect(0, 20, 191, 18))
        self.bt_adicionarproduto.setStyleSheet("color: white;\n"
"background-color:none;\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.bt_adicionarproduto.setObjectName("bt_adicionarproduto")
        self.tx_descriproduto = QtWidgets.QLineEdit(self.frame_5)
        self.tx_descriproduto.setGeometry(QtCore.QRect(10, 50, 211, 32))
        self.tx_descriproduto.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_descriproduto.setObjectName("tx_descriproduto")
        self.bt_veritem = QtWidgets.QPushButton(self.frame_5)
        self.bt_veritem.setGeometry(QtCore.QRect(230, 50, 34, 30))
        self.bt_veritem.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_veritem.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_veritem.setIcon(icon6)
        self.bt_veritem.setIconSize(QtCore.QSize(30, 30))
        self.bt_veritem.setObjectName("bt_veritem")
        self.spin_quantidade = QtWidgets.QSpinBox(self.frame_5)
        self.spin_quantidade.setGeometry(QtCore.QRect(330, 50, 120, 32))
        self.spin_quantidade.setMinimumSize(QtCore.QSize(120, 0))
        self.spin_quantidade.setMaximumSize(QtCore.QSize(120, 16777215))
        self.spin_quantidade.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spin_quantidade.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"border: 2px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 0 8px;\n"
"background-color: rgb(255, 255, 255);")
        self.spin_quantidade.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spin_quantidade.setProperty("showGroupSeparator", False)
        self.spin_quantidade.setMaximum(1200)
        self.spin_quantidade.setProperty("value", 1)
        self.spin_quantidade.setObjectName("spin_quantidade")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(330, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";\n"
"background:none;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.frame_5)
        self.tb_vendaGrupo = QtWidgets.QTableWidget(self.widget_3)
        self.tb_vendaGrupo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tb_vendaGrupo.setStyleSheet("QTableView{\n"
"background: #F1F1F1;\n"
"color: black;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"border:1px solid;\n"
"    selection-color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(85, 170, 255);\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border:none;\n"
"border-bottom: 2px solid black;\n"
"border-top:2px solid black;\n"
"padding:5px 0px;\n"
"text-transform: uppercase\n"
"}\n"
"\n"
"")
        self.tb_vendaGrupo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_vendaGrupo.setTabKeyNavigation(False)
        self.tb_vendaGrupo.setProperty("showDropIndicator", False)
        self.tb_vendaGrupo.setAlternatingRowColors(True)
        self.tb_vendaGrupo.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tb_vendaGrupo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_vendaGrupo.setShowGrid(True)
        self.tb_vendaGrupo.setGridStyle(QtCore.Qt.SolidLine)
        self.tb_vendaGrupo.setObjectName("tb_vendaGrupo")
        self.tb_vendaGrupo.setColumnCount(5)
        self.tb_vendaGrupo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_vendaGrupo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_vendaGrupo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_vendaGrupo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_vendaGrupo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_vendaGrupo.setHorizontalHeaderItem(4, item)
        self.tb_vendaGrupo.horizontalHeader().setDefaultSectionSize(185)
        self.tb_vendaGrupo.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tb_vendaGrupo)
        self.frame_3 = QtWidgets.QFrame(self.widget_3)
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:1 rgba(255, 0, 0, 216));\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.tx_Quantidade = QtWidgets.QLineEdit(self.frame_3)
        self.tx_Quantidade.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_Quantidade.setStyleSheet("QLineEdit{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(255, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"font-size: 20px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border:none;\n"
"\n"
"padding:6px;\n"
"\n"
"}\n"
"")
        self.tx_Quantidade.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_Quantidade.setObjectName("tx_Quantidade")
        self.horizontalLayout_5.addWidget(self.tx_Quantidade)
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.db_vendas = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.db_vendas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_vendas.setStyleSheet("    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:0 rgba(255, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"font-size: 20px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border:none;\n"
"\n"
"padding:6px;")
        self.db_vendas.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_vendas.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_vendas.setProperty("showGroupSeparator", True)
        self.db_vendas.setMaximum(999999.0)
        self.db_vendas.setObjectName("db_vendas")
        self.horizontalLayout_5.addWidget(self.db_vendas)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"text-transform: uppercase;\n"
"\n"
"    background-color: rgb(231, 231, 231);\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listGrupoProdutos = QtWidgets.QListWidget(self.widget_4)
        self.listGrupoProdutos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listGrupoProdutos.setStyleSheet("QLabel{\n"
"    \n"
"    font: 10pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"QListWidget\n"
"{\n"
"border : 1px solid black;\n"
"background :#e1e1e1 ;\n"
"padding:10px;\n"
"color: rgb(0, 0, 0);\n"
"}\n"
" QListView::item:selected\n"
"{\n"
"    background-color: rgb(249, 249, 249);\n"
"color:white;\n"
"border-bottom:2px solid red;\n"
"\n"
"}\n"
"\n"
"QListView::item{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"    border-left:2px solid blue;\n"
"border-top-right-radius: 2px;\n"
"border-bottom-right-radius: 2px;\n"
"margin:5px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    text-align:center;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    \n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color: rgb(0, 85, 255);\n"
"padding:10px 15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"")
        self.listGrupoProdutos.setFrameShape(QtWidgets.QFrame.Box)
        self.listGrupoProdutos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listGrupoProdutos.setProperty("showDropIndicator", False)
        self.listGrupoProdutos.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listGrupoProdutos.setAlternatingRowColors(False)
        self.listGrupoProdutos.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listGrupoProdutos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listGrupoProdutos.setIconSize(QtCore.QSize(80, 80))
        self.listGrupoProdutos.setTextElideMode(QtCore.Qt.ElideRight)
        self.listGrupoProdutos.setMovement(QtWidgets.QListView.Free)
        self.listGrupoProdutos.setFlow(QtWidgets.QListView.LeftToRight)
        self.listGrupoProdutos.setProperty("isWrapping", True)
        self.listGrupoProdutos.setResizeMode(QtWidgets.QListView.Adjust)
        self.listGrupoProdutos.setLayoutMode(QtWidgets.QListView.Batched)
        self.listGrupoProdutos.setGridSize(QtCore.QSize(220, 250))
        self.listGrupoProdutos.setViewMode(QtWidgets.QListView.IconMode)
        self.listGrupoProdutos.setUniformItemSizes(False)
        self.listGrupoProdutos.setBatchSize(100)
        self.listGrupoProdutos.setWordWrap(False)
        self.listGrupoProdutos.setItemAlignment(QtCore.Qt.AlignHCenter)
        self.listGrupoProdutos.setObjectName("listGrupoProdutos")
        self.verticalLayout.addWidget(self.listGrupoProdutos)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_5.addWidget(self.widget_2)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.fundo)

        self.retranslateUi(Formrestaurante)
        QtCore.QMetaObject.connectSlotsByName(Formrestaurante)
        Formrestaurante.setTabOrder(self.spin_garcon, self.tx_descriproduto)
        Formrestaurante.setTabOrder(self.tx_descriproduto, self.spin_quantidade)
        Formrestaurante.setTabOrder(self.spin_quantidade, self.bt_adicionarproduto)
        Formrestaurante.setTabOrder(self.bt_adicionarproduto, self.toolButton_3)
        Formrestaurante.setTabOrder(self.toolButton_3, self.bt_delete)
        Formrestaurante.setTabOrder(self.bt_delete, self.toolButton_4)

    def retranslateUi(self, Formrestaurante):
        _translate = QtCore.QCoreApplication.translate
        Formrestaurante.setWindowTitle(_translate("Formrestaurante", "RESTAURANTE"))
        self.toolButton.setText(_translate("Formrestaurante", "caixa"))
        self.bt_criamesa.setText(_translate("Formrestaurante", "ABRIR MESA (F4)"))
        self.bt_criamesa.setShortcut(_translate("Formrestaurante", "F4"))
        self.bt_fechamesa.setText(_translate("Formrestaurante", "fecha mesa (f6)"))
        self.toolButton_4.setText(_translate("Formrestaurante", "entregas"))
        self.toolButton_3.setText(_translate("Formrestaurante", "OPÇOES"))
        self.label_4.setText(_translate("Formrestaurante", "mesa:0000"))
        self.label_5.setText(_translate("Formrestaurante", "atendente:garçom"))
        self.bt_finalizaVenda.setText(_translate("Formrestaurante", "FINALIZA VENDA (f12)"))
        self.bt_finalizaVenda.setShortcut(_translate("Formrestaurante", "F12"))
        self.bt_delete.setToolTip(_translate("Formrestaurante", "deleta produto grade"))
        self.bt_delete.setText(_translate("Formrestaurante", "delete (del)"))
        self.bt_delete.setShortcut(_translate("Formrestaurante", "Del"))
        self.bt_adicionarproduto.setText(_translate("Formrestaurante", "adicionar produto"))
        self.bt_veritem.setToolTip(_translate("Formrestaurante", "apera f5 ver itens"))
        self.bt_veritem.setShortcut(_translate("Formrestaurante", "F5"))
        self.label_6.setText(_translate("Formrestaurante", "quantidade"))
        item = self.tb_vendaGrupo.horizontalHeaderItem(0)
        item.setText(_translate("Formrestaurante", "CODBR"))
        item = self.tb_vendaGrupo.horizontalHeaderItem(1)
        item.setText(_translate("Formrestaurante", "descriçao"))
        item = self.tb_vendaGrupo.horizontalHeaderItem(2)
        item.setText(_translate("Formrestaurante", "QTD"))
        item = self.tb_vendaGrupo.horizontalHeaderItem(3)
        item.setText(_translate("Formrestaurante", "VL UNID"))
        item = self.tb_vendaGrupo.horizontalHeaderItem(4)
        item.setText(_translate("Formrestaurante", "VL TOTAL"))
        self.label_2.setText(_translate("Formrestaurante", "qtd"))
        self.tx_Quantidade.setText(_translate("Formrestaurante", "0,00"))
        self.label.setText(_translate("Formrestaurante", "vl total"))
        self.db_vendas.setPrefix(_translate("Formrestaurante", "R$ "))
        self.listGrupoProdutos.setSortingEnabled(False)
