# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormFinalizaVenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormFinalizarVenda(object):
    def setupUi(self, FormFinalizarVenda):
        FormFinalizarVenda.setObjectName("FormFinalizarVenda")
        FormFinalizarVenda.resize(620, 618)
        FormFinalizarVenda.setStyleSheet("QWidget#FormFinalizarVenda{\n"
"    background-color: rgb(0, 0, 0,200);\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(FormFinalizarVenda)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(FormFinalizarVenda)
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"    background-color: rgb(0, 0, 0,200);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(500, 600))
        self.widget_3.setMaximumSize(QtCore.QSize(500, 600))
        self.widget_3.setObjectName("widget_3")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setGeometry(QtCore.QRect(30, 120, 411, 451))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("QWidget{\n"
"text-transform: uppercase;\n"
"    background-color: rgb(229, 229, 229);\n"
"border:1px solid blue;\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"border-top-left-radius:20px\n"
"\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("QFrame#frame{\n"
"border:none;\n"
"}\n"
"QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #277298;\n"
"border: none;\n"
"}\n"
"QDoubleSpinBox{\n"
"background-color: rgb(255, 255, 127);\n"
"font-size: 24px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"QComboBox{\n"
"border:1px solid;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tx_valortotal = QtWidgets.QDoubleSpinBox(self.frame)
        self.tx_valortotal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_valortotal.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_valortotal.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_valortotal.setProperty("showGroupSeparator", True)
        self.tx_valortotal.setMaximum(999999999999.0)
        self.tx_valortotal.setObjectName("tx_valortotal")
        self.verticalLayout.addWidget(self.tx_valortotal)
        self.lb_FormVenda_32 = QtWidgets.QLabel(self.frame)
        self.lb_FormVenda_32.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #277298;\n"
"border: none\n"
"}")
        self.lb_FormVenda_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_FormVenda_32.setObjectName("lb_FormVenda_32")
        self.verticalLayout.addWidget(self.lb_FormVenda_32)
        self.cb_tipoDocumento = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_tipoDocumento.setFont(font)
        self.cb_tipoDocumento.setStyleSheet("border-radius:0px;")
        self.cb_tipoDocumento.setObjectName("cb_tipoDocumento")
        self.verticalLayout.addWidget(self.cb_tipoDocumento)
        self.lb_FormVenda_31 = QtWidgets.QLabel(self.frame)
        self.lb_FormVenda_31.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #277298;\n"
"border: none\n"
"}")
        self.lb_FormVenda_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_FormVenda_31.setObjectName("lb_FormVenda_31")
        self.verticalLayout.addWidget(self.lb_FormVenda_31)
        self.cb_FormaPagamento = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_FormaPagamento.setFont(font)
        self.cb_FormaPagamento.setStyleSheet("border-radius:0px;")
        self.cb_FormaPagamento.setObjectName("cb_FormaPagamento")
        self.verticalLayout.addWidget(self.cb_FormaPagamento)
        self.lb_FormVenda_33 = QtWidgets.QLabel(self.frame)
        self.lb_FormVenda_33.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #277298;\n"
"border: none\n"
"}")
        self.lb_FormVenda_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_FormVenda_33.setObjectName("lb_FormVenda_33")
        self.verticalLayout.addWidget(self.lb_FormVenda_33)
        self.tx_desconto = QtWidgets.QDoubleSpinBox(self.frame)
        self.tx_desconto.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_desconto.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_desconto.setProperty("showGroupSeparator", True)
        self.tx_desconto.setMaximum(999999999.0)
        self.tx_desconto.setObjectName("tx_desconto")
        self.verticalLayout.addWidget(self.tx_desconto)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tx_subTotal = QtWidgets.QDoubleSpinBox(self.frame)
        self.tx_subTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_subTotal.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.tx_subTotal.setProperty("showGroupSeparator", True)
        self.tx_subTotal.setMaximum(9999999999.0)
        self.tx_subTotal.setObjectName("tx_subTotal")
        self.verticalLayout.addWidget(self.tx_subTotal)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_finalizar = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.bt_finalizar.setFont(font)
        self.bt_finalizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_finalizar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_finalizar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bt_finalizar.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF;\n"
"padding:5px ;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_finalizar.setIconSize(QtCore.QSize(30, 30))
        self.bt_finalizar.setObjectName("bt_finalizar")
        self.horizontalLayout.addWidget(self.bt_finalizar)
        self.bt_cancelar = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.bt_cancelar.setFont(font)
        self.bt_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.bt_cancelar.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF;\n"
"padding:5px ;\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-left-radius:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        self.bt_cancelar.setIconSize(QtCore.QSize(30, 30))
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.horizontalLayout.addWidget(self.bt_cancelar)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget_3)
        self.frame_2.setGeometry(QtCore.QRect(250, 0, 191, 161))
        self.frame_2.setStyleSheet("QFrame{\n"
"    image: url(:/telainicial/telainicial/logo.jpg);\n"
"background-color:none;\n"
"border:none;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(150, 260, 161, 191))
        self.widget_4.setStyleSheet("QWidget#widget_4{\n"
"text-transform: uppercase;\n"
"    background-color: rgb(229, 229, 229);\n"
"border:2px solid blue;\n"
"\n"
"\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rd_pedido = QtWidgets.QRadioButton(self.widget_4)
        self.rd_pedido.setChecked(True)
        self.rd_pedido.setObjectName("rd_pedido")
        self.verticalLayout_2.addWidget(self.rd_pedido)
        self.rd_nfce = QtWidgets.QRadioButton(self.widget_4)
        self.rd_nfce.setObjectName("rd_nfce")
        self.verticalLayout_2.addWidget(self.rd_nfce)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.bt_finalizaped = QtWidgets.QPushButton(self.widget_4)
        self.bt_finalizaped.setObjectName("bt_finalizaped")
        self.verticalLayout_2.addWidget(self.bt_finalizaped)
        self.widget.raise_()
        self.widget_4.raise_()
        self.frame_2.raise_()
        self.horizontalLayout_3.addWidget(self.widget_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.actioncliente = QtWidgets.QAction(FormFinalizarVenda)
        self.actioncliente.setObjectName("actioncliente")

        self.retranslateUi(FormFinalizarVenda)
        QtCore.QMetaObject.connectSlotsByName(FormFinalizarVenda)
        FormFinalizarVenda.setTabOrder(self.tx_desconto, self.tx_subTotal)
        FormFinalizarVenda.setTabOrder(self.tx_subTotal, self.cb_tipoDocumento)
        FormFinalizarVenda.setTabOrder(self.cb_tipoDocumento, self.cb_FormaPagamento)

    def retranslateUi(self, FormFinalizarVenda):
        _translate = QtCore.QCoreApplication.translate
        FormFinalizarVenda.setWindowTitle(_translate("FormFinalizarVenda", "FormFinallizaVenda"))
        self.label.setText(_translate("FormFinalizarVenda", "valor total"))
        self.lb_FormVenda_32.setText(_translate("FormFinalizarVenda", "tipo documento"))
        self.lb_FormVenda_31.setText(_translate("FormFinalizarVenda", "Forma pagamento"))
        self.lb_FormVenda_33.setText(_translate("FormFinalizarVenda", "descontoR$"))
        self.label_2.setText(_translate("FormFinalizarVenda", "sub total"))
        self.bt_finalizar.setText(_translate("FormFinalizarVenda", "finalizar (F2)"))
        self.bt_finalizar.setShortcut(_translate("FormFinalizarVenda", "F2"))
        self.bt_cancelar.setText(_translate("FormFinalizarVenda", "cancelar (ESC)"))
        self.bt_cancelar.setShortcut(_translate("FormFinalizarVenda", "Esc"))
        self.rd_pedido.setText(_translate("FormFinalizarVenda", "PEDIDO"))
        self.rd_nfce.setText(_translate("FormFinalizarVenda", "NFCE"))
        self.bt_finalizaped.setText(_translate("FormFinalizarVenda", "finalizar"))
        self.actioncliente.setText(_translate("FormFinalizarVenda", "cliente"))
