# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/FormInicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicial(object):
    def setupUi(self, Inicial):
        Inicial.setObjectName("Inicial")
        Inicial.resize(1499, 863)
        Inicial.setMinimumSize(QtCore.QSize(240, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/fundo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Inicial.setWindowIcon(icon)
        Inicial.setAutoFillBackground(False)
        Inicial.setStyleSheet("")
        Inicial.setIconSize(QtCore.QSize(60, 60))
        self.centralwidget = QtWidgets.QWidget(Inicial)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setStyleSheet("text-transform: uppercase;\n"
"background-color: rgb(236, 236, 236)")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.topdados = QtWidgets.QFrame(self.centralwidget)
        self.topdados.setMinimumSize(QtCore.QSize(0, 0))
        self.topdados.setStyleSheet("QFrame#topdados{\n"
"    background-color: rgb(232, 232, 232);\n"
"    border:0px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"border:none;\n"
"    }\n"
"    QPushButton:hover {\n"
"    background-color: #0864ae;\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:1 rgba(255, 255, 255, 111));\n"
"}")
        self.topdados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topdados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topdados.setObjectName("topdados")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.topdados)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_17 = QtWidgets.QFrame(self.topdados)
        self.frame_17.setMinimumSize(QtCore.QSize(1200, 0))
        self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"        background-color:#005a9e;\n"
"border :3px solid #005a9e;\n"
" border-top-left-radius :0px;\n"
"border-top-right-radius : 0px; \n"
" border-bottom-left-radius : 0px;\n"
" border-bottom-right-radius :25px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
" background-color:#005a9e;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_17)
        self.label_8.setMaximumSize(QtCore.QSize(30, 30))
        self.label_8.setPixmap(QtGui.QPixmap(":/telainicial/telainicial/menorwindow10.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lb_topico = QtWidgets.QLabel(self.frame_17)
        self.lb_topico.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_topico.setText("")
        self.lb_topico.setObjectName("lb_topico")
        self.horizontalLayout_7.addWidget(self.lb_topico)
        self.horizontalLayout_5.addWidget(self.frame_17)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.frame_move = QtWidgets.QFrame(self.topdados)
        self.frame_move.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_move.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_move.setStyleSheet("background-color: none;")
        self.frame_move.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_move.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_move.setObjectName("frame_move")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_move)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_move)
        self.label.setStyleSheet("font: 900 26pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.horizontalLayout_5.addWidget(self.frame_move)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.topdados)
        self.frame.setMinimumSize(QtCore.QSize(120, 0))
        self.frame.setStyleSheet("QFrame{\n"
"            background-color:#005a9e;\n"
"border :3px solid #005a9e;\n"
" border-top-left-radius :0px;\n"
"border-top-right-radius : 0px; \n"
" border-bottom-left-radius : 25px;\n"
" border-bottom-right-radius : 0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_minimize = QtWidgets.QPushButton(self.frame)
        self.bt_minimize.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimize.setIcon(icon1)
        self.bt_minimize.setIconSize(QtCore.QSize(20, 20))
        self.bt_minimize.setObjectName("bt_minimize")
        self.horizontalLayout_6.addWidget(self.bt_minimize)
        self.bt_closer = QtWidgets.QPushButton(self.frame)
        self.bt_closer.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.bt_closer.setFont(font)
        self.bt_closer.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_closer.setStyleSheet("")
        self.bt_closer.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/menuopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_closer.setIcon(icon2)
        self.bt_closer.setIconSize(QtCore.QSize(20, 20))
        self.bt_closer.setObjectName("bt_closer")
        self.horizontalLayout_6.addWidget(self.bt_closer)
        self.horizontalLayout_5.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.topdados)
        self.frame_12 = QtWidgets.QFrame(self.centralwidget)
        self.frame_12.setStyleSheet("QFrame{\n"
"      background-color:#005a9e;\n"
"}\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.framemenuaction = QtWidgets.QFrame(self.frame_12)
        self.framemenuaction.setMaximumSize(QtCore.QSize(16777215, 50))
        self.framemenuaction.setStyleSheet("QFrame{\n"
"\n"
"        background-color:#005a9e;\n"
"}\n"
"\n"
"QToolButton{\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-size: 13px;\n"
"border:none;\n"
"padding:5px 15px\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: #0864ae;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    background-color: #0864ae;\n"
"}\n"
"\n"
"\n"
"QMenu{\n"
"    background-color: rgb(0, 85, 255);\n"
"text-transform: uppercase;\n"
"    color: rgb(0, 0, 0);\n"
"    selection-color: rgb(255, 255, 255);\n"
"color:white;\n"
"}\n"
"QMenu::item {\n"
"    padding: 2px 25px 2px 20px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"QMenu::item:selected {\n"
"\n"
"border:none;\n"
"background-color: #0864ae;\n"
"}\n"
"\n"
"")
        self.framemenuaction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framemenuaction.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framemenuaction.setObjectName("framemenuaction")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.framemenuaction)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tollcadastro = QtWidgets.QToolButton(self.framemenuaction)
        self.tollcadastro.setMinimumSize(QtCore.QSize(123, 0))
        self.tollcadastro.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/cadastrosgeral.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tollcadastro.setIcon(icon3)
        self.tollcadastro.setIconSize(QtCore.QSize(20, 20))
        self.tollcadastro.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.tollcadastro.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tollcadastro.setObjectName("tollcadastro")
        self.horizontalLayout_4.addWidget(self.tollcadastro)
        self.tb_vendas = QtWidgets.QToolButton(self.framemenuaction)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/pdv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_vendas.setIcon(icon4)
        self.tb_vendas.setIconSize(QtCore.QSize(20, 20))
        self.tb_vendas.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.tb_vendas.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tb_vendas.setObjectName("tb_vendas")
        self.horizontalLayout_4.addWidget(self.tb_vendas)
        self.toolfinanceiro = QtWidgets.QToolButton(self.framemenuaction)
        self.toolfinanceiro.setFocusPolicy(QtCore.Qt.NoFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/receber.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolfinanceiro.setIcon(icon5)
        self.toolfinanceiro.setIconSize(QtCore.QSize(20, 20))
        self.toolfinanceiro.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolfinanceiro.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolfinanceiro.setObjectName("toolfinanceiro")
        self.horizontalLayout_4.addWidget(self.toolfinanceiro)
        self.tollutitilitarios = QtWidgets.QToolButton(self.framemenuaction)
        self.tollutitilitarios.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/utilitariosbranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tollutitilitarios.setIcon(icon6)
        self.tollutitilitarios.setIconSize(QtCore.QSize(20, 20))
        self.tollutitilitarios.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.tollutitilitarios.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tollutitilitarios.setObjectName("tollutitilitarios")
        self.horizontalLayout_4.addWidget(self.tollutitilitarios)
        self.tolconfiguracao = QtWidgets.QToolButton(self.framemenuaction)
        self.tolconfiguracao.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/configbranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tolconfiguracao.setIcon(icon7)
        self.tolconfiguracao.setIconSize(QtCore.QSize(20, 20))
        self.tolconfiguracao.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.tolconfiguracao.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tolconfiguracao.setObjectName("tolconfiguracao")
        self.horizontalLayout_4.addWidget(self.tolconfiguracao)
        self.horizontalLayout_2.addWidget(self.framemenuaction)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("QFrame#frame_3{border:none}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:#005a9e;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_Menu = QtWidgets.QPushButton(self.frame_2)
        self.bt_Menu.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_Menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_Menu.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_Menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_Menu.setAutoFillBackground(False)
        self.bt_Menu.setStyleSheet("QPushButton {\n"
"text-align: left;\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"border:none;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"\n"
"    background-color: #0864ae;\n"
"    }")
        self.bt_Menu.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/novo/telainicial/menuaberto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/novo/telainicial/menuopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.bt_Menu.setIcon(icon8)
        self.bt_Menu.setIconSize(QtCore.QSize(25, 25))
        self.bt_Menu.setObjectName("bt_Menu")
        self.verticalLayout_2.addWidget(self.bt_Menu)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_LT = QtWidgets.QFrame(self.frame_3)
        self.frame_LT.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_LT.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_LT.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_LT.setStyleSheet("QFrame#frame_LT{\n"
"border:none;\n"
"background-color:#005a9e;\n"
"}\n"
"QWidget{\n"
"border:none;\n"
"background-color:#005a9e;\n"
"}\n"
"\n"
"QToolButton{\n"
"\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-size: 9px;\n"
"        font-weight: bold;\n"
"\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"    background-color: #0864ae;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"    background-color: #0864ae;\n"
"}\n"
"\n"
"QPushButton {\n"
"text-align: left;\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-size: 12px;\n"
"        font-weight: bold;\n"
"        padding: 2px;\n"
"border:none;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"\n"
"    background-color: #0864ae;\n"
"    }")
        self.frame_LT.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LT.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LT.setObjectName("frame_LT")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_LT)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_Cadastros = QtWidgets.QPushButton(self.frame_LT)
        self.bt_Cadastros.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/setabaixo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Cadastros.setIcon(icon9)
        self.bt_Cadastros.setIconSize(QtCore.QSize(40, 20))
        self.bt_Cadastros.setObjectName("bt_Cadastros")
        self.verticalLayout.addWidget(self.bt_Cadastros)
        self.widgetCadastro = QtWidgets.QWidget(self.frame_LT)
        self.widgetCadastro.setMaximumSize(QtCore.QSize(300, 0))
        self.widgetCadastro.setStyleSheet("")
        self.widgetCadastro.setObjectName("widgetCadastro")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widgetCadastro)
        self.verticalLayout_15.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widgetCadastro)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(240, 0))
        self.scrollArea_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea_2.setStyleSheet("border:none")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 223, 131))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.bt_estoqque = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.bt_estoqque.setMinimumSize(QtCore.QSize(110, 0))
        self.bt_estoqque.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/estoquebranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_estoqque.setIcon(icon10)
        self.bt_estoqque.setIconSize(QtCore.QSize(25, 25))
        self.bt_estoqque.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_estoqque.setObjectName("bt_estoqque")
        self.verticalLayout_24.addWidget(self.bt_estoqque)
        self.bt_clientes = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.bt_clientes.setMinimumSize(QtCore.QSize(110, 0))
        self.bt_clientes.setStyleSheet("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/clientesbranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_clientes.setIcon(icon11)
        self.bt_clientes.setIconSize(QtCore.QSize(25, 25))
        self.bt_clientes.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_clientes.setObjectName("bt_clientes")
        self.verticalLayout_24.addWidget(self.bt_clientes)
        self.bt_funcionario = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.bt_funcionario.setMinimumSize(QtCore.QSize(110, 0))
        self.bt_funcionario.setMaximumSize(QtCore.QSize(110, 16777215))
        self.bt_funcionario.setStyleSheet("font: 6pt \"Segoe UI\";")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/funcionariobranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_funcionario.setIcon(icon12)
        self.bt_funcionario.setIconSize(QtCore.QSize(25, 25))
        self.bt_funcionario.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bt_funcionario.setObjectName("bt_funcionario")
        self.verticalLayout_24.addWidget(self.bt_funcionario)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_15.addWidget(self.scrollArea_2)
        self.verticalLayout.addWidget(self.widgetCadastro)
        self.BtFinanceiros = QtWidgets.QPushButton(self.frame_LT)
        self.BtFinanceiros.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.BtFinanceiros.setIcon(icon9)
        self.BtFinanceiros.setIconSize(QtCore.QSize(40, 20))
        self.BtFinanceiros.setObjectName("BtFinanceiros")
        self.verticalLayout.addWidget(self.BtFinanceiros)
        self.frameFinanceiro = QtWidgets.QFrame(self.frame_LT)
        self.frameFinanceiro.setMaximumSize(QtCore.QSize(300, 0))
        self.frameFinanceiro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFinanceiro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFinanceiro.setObjectName("frameFinanceiro")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frameFinanceiro)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.scrollArea = QtWidgets.QScrollArea(self.frameFinanceiro)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setStyleSheet("border:none")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 110, 137))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.tb_receber = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.tb_receber.setMinimumSize(QtCore.QSize(110, 0))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/receberbranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_receber.setIcon(icon13)
        self.tb_receber.setIconSize(QtCore.QSize(30, 30))
        self.tb_receber.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tb_receber.setObjectName("tb_receber")
        self.verticalLayout_25.addWidget(self.tb_receber)
        self.tb_caixa = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.tb_caixa.setMinimumSize(QtCore.QSize(110, 0))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/caixabranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_caixa.setIcon(icon14)
        self.tb_caixa.setIconSize(QtCore.QSize(25, 25))
        self.tb_caixa.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tb_caixa.setObjectName("tb_caixa")
        self.verticalLayout_25.addWidget(self.tb_caixa)
        self.tb_pagarConta = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.tb_pagarConta.setMinimumSize(QtCore.QSize(0, 0))
        self.tb_pagarConta.setMaximumSize(QtCore.QSize(110, 16777215))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/apagabranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_pagarConta.setIcon(icon15)
        self.tb_pagarConta.setIconSize(QtCore.QSize(25, 25))
        self.tb_pagarConta.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tb_pagarConta.setObjectName("tb_pagarConta")
        self.verticalLayout_25.addWidget(self.tb_pagarConta)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_21.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frameFinanceiro)
        self.bt_entradasnotas = QtWidgets.QPushButton(self.frame_LT)
        self.bt_entradasnotas.setIcon(icon9)
        self.bt_entradasnotas.setIconSize(QtCore.QSize(40, 20))
        self.bt_entradasnotas.setObjectName("bt_entradasnotas")
        self.verticalLayout.addWidget(self.bt_entradasnotas)
        self.frameentradanota = QtWidgets.QFrame(self.frame_LT)
        self.frameentradanota.setMaximumSize(QtCore.QSize(250, 0))
        self.frameentradanota.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frameentradanota.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameentradanota.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameentradanota.setObjectName("frameentradanota")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frameentradanota)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.frameentradanota)
        self.scrollArea_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea_3.setStyleSheet("border:none")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 110, 44))
        self.scrollAreaWidgetContents_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.tb_entradanota = QtWidgets.QToolButton(self.scrollAreaWidgetContents_3)
        self.tb_entradanota.setMinimumSize(QtCore.QSize(110, 0))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/entradanotabranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_entradanota.setIcon(icon16)
        self.tb_entradanota.setIconSize(QtCore.QSize(25, 25))
        self.tb_entradanota.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tb_entradanota.setObjectName("tb_entradanota")
        self.verticalLayout_26.addWidget(self.tb_entradanota)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem6)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_22.addWidget(self.scrollArea_3)
        self.verticalLayout.addWidget(self.frameentradanota)
        self.Bt_vendas = QtWidgets.QPushButton(self.frame_LT)
        self.Bt_vendas.setIcon(icon9)
        self.Bt_vendas.setIconSize(QtCore.QSize(40, 20))
        self.Bt_vendas.setObjectName("Bt_vendas")
        self.verticalLayout.addWidget(self.Bt_vendas)
        self.FrameVenda = QtWidgets.QFrame(self.frame_LT)
        self.FrameVenda.setMaximumSize(QtCore.QSize(300, 0))
        self.FrameVenda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameVenda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameVenda.setObjectName("FrameVenda")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.FrameVenda)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.FrameVenda)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(240, 0))
        self.scrollArea_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 223, 50))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.tb_analasivenda = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        self.tb_analasivenda.setMinimumSize(QtCore.QSize(110, 0))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/analisevendarbranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_analasivenda.setIcon(icon17)
        self.tb_analasivenda.setIconSize(QtCore.QSize(25, 25))
        self.tb_analasivenda.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tb_analasivenda.setObjectName("tb_analasivenda")
        self.verticalLayout_27.addWidget(self.tb_analasivenda)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem7)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_23.addWidget(self.scrollArea_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.FrameVenda)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_3.addWidget(self.frame_LT)
        self.fundo = QtWidgets.QFrame(self.frame_3)
        self.fundo.setMinimumSize(QtCore.QSize(0, 0))
        self.fundo.setStyleSheet("QFrame#fundo{border:none;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.fundo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo.setObjectName("fundo")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fundo)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.fundo)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #C2C7CB;\n"
"    position: absolute;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 1px solid #C4C4C3;\n"
"    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.inicialpage = QtWidgets.QWidget()
        self.inicialpage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.inicialpage.setStyleSheet("")
        self.inicialpage.setObjectName("inicialpage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.inicialpage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.inicialpage)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.widget_5 = QtWidgets.QWidget(self.frame_8)
        self.widget_5.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#005a92;\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"border:none;\n"
"margin-left:6px;\n"
"background-color:#005a92;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.frame_10 = QtWidgets.QFrame(self.widget_5)
        self.frame_10.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_10.addWidget(self.label_6)
        self.db_CaixaValor = QtWidgets.QDoubleSpinBox(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.db_CaixaValor.setFont(font)
        self.db_CaixaValor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_CaixaValor.setStyleSheet("background-color:#005a92;\n"
"\n"
"border:none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.db_CaixaValor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_CaixaValor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_CaixaValor.setProperty("showGroupSeparator", True)
        self.db_CaixaValor.setMaximum(99999999999.0)
        self.db_CaixaValor.setObjectName("db_CaixaValor")
        self.verticalLayout_10.addWidget(self.db_CaixaValor)
        self.horizontalLayout_9.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.widget_5)
        self.frame_9.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.lb_Vendas = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_Vendas.setFont(font)
        self.lb_Vendas.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_Vendas.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Vendas.setObjectName("lb_Vendas")
        self.verticalLayout_9.addWidget(self.lb_Vendas)
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(self.widget_5)
        self.frame_7.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.lb_quantEstoque = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_quantEstoque.setFont(font)
        self.lb_quantEstoque.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_quantEstoque.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_quantEstoque.setObjectName("lb_quantEstoque")
        self.verticalLayout_7.addWidget(self.lb_quantEstoque)
        self.horizontalLayout_9.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.widget_5)
        self.frame_6.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.lb_quantClientes = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_quantClientes.setFont(font)
        self.lb_quantClientes.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_quantClientes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_quantClientes.setObjectName("lb_quantClientes")
        self.verticalLayout_6.addWidget(self.lb_quantClientes)
        self.horizontalLayout_9.addWidget(self.frame_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_8.addWidget(self.widget_5)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_11 = QtWidgets.QFrame(self.inicialpage)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_20.addWidget(self.label_16)
        self.frame_5 = QtWidgets.QFrame(self.frame_11)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.dataRelatorio = QtWidgets.QDateEdit(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.dataRelatorio.setFont(font)
        self.dataRelatorio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dataRelatorio.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(55, 110, 165);")
        self.dataRelatorio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dataRelatorio.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.dataRelatorio.setKeyboardTracking(True)
        self.dataRelatorio.setCalendarPopup(True)
        self.dataRelatorio.setDate(QtCore.QDate(2000, 2, 1))
        self.dataRelatorio.setObjectName("dataRelatorio")
        self.horizontalLayout_11.addWidget(self.dataRelatorio)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.verticalLayout_20.addWidget(self.frame_5)
        self.widget_12 = QtWidgets.QWidget(self.frame_11)
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 318))
        self.widget_12.setStyleSheet("QFrame{\n"
"\n"
"    background-color:#005a92;\n"
"color:white;\n"
"}\n"
"QLabel{\n"
"border:none;\n"
"margin-left:6px;\n"
"background-color:#005a92;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"\n"
"    background-color:#005a92;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    color: white;\n"
"}\n"
"QPushButton:disabled {\n"
"  background-color: rgb(203, 203, 203);}\n"
"QPushButton:hover {\n"
"  background-color: rgb(254, 53, 66);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
" background-color: rgb(181, 24, 49);\n"
"}\n"
"QTableView {\n"
"    selection-color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QTableView::item {\n"
"\n"
"    selection-color: rgb(255, 0, 0);\n"
"border-bottom:1px solid black;\n"
"padding: 2px;\n"
"\n"
"}\n"
"\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"\n"
"font-size: 13px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border:none;\n"
"border-bottom: 2px solid black;\n"
"border-top:2px solid black;\n"
"padding:5px 0px;\n"
"text-transform: uppercase\n"
"}")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.widget_4 = QtWidgets.QWidget(self.widget_12)
        self.widget_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_13 = QtWidgets.QFrame(self.widget_4)
        self.frame_13.setMinimumSize(QtCore.QSize(300, 80))
        self.frame_13.setMaximumSize(QtCore.QSize(300, 80))
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_16.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.bt_caixa = QtWidgets.QPushButton(self.frame_13)
        self.bt_caixa.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_caixa.setStyleSheet("")
        self.bt_caixa.setObjectName("bt_caixa")
        self.verticalLayout_16.addWidget(self.bt_caixa)
        self.db_CaixaValordiario = QtWidgets.QDoubleSpinBox(self.frame_13)
        self.db_CaixaValordiario.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.db_CaixaValordiario.setFont(font)
        self.db_CaixaValordiario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_CaixaValordiario.setStyleSheet("\n"
"    background-color:#005a92;\n"
"\n"
"font: 14pt \"Segoe UI\";\n"
"border:none;\n"
"color: rgb(255, 255, 255);")
        self.db_CaixaValordiario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_CaixaValordiario.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_CaixaValordiario.setProperty("showGroupSeparator", True)
        self.db_CaixaValordiario.setMaximum(99999999999.0)
        self.db_CaixaValordiario.setObjectName("db_CaixaValordiario")
        self.verticalLayout_16.addWidget(self.db_CaixaValordiario)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.widget_4)
        self.tableWidget_4.setMaximumSize(QtCore.QSize(300, 0))
        self.tableWidget_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.verticalLayout_14.addWidget(self.tableWidget_4)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem15)
        self.horizontalLayout_10.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget_12)
        self.widget_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_14 = QtWidgets.QFrame(self.widget_3)
        self.frame_14.setMinimumSize(QtCore.QSize(300, 80))
        self.frame_14.setMaximumSize(QtCore.QSize(300, 80))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_17.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.bt_vervenda = QtWidgets.QPushButton(self.frame_14)
        self.bt_vervenda.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_vervenda.setObjectName("bt_vervenda")
        self.verticalLayout_17.addWidget(self.bt_vervenda)
        self.lb_Vendasdiario = QtWidgets.QLabel(self.frame_14)
        self.lb_Vendasdiario.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.lb_Vendasdiario.setFont(font)
        self.lb_Vendasdiario.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lb_Vendasdiario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Vendasdiario.setObjectName("lb_Vendasdiario")
        self.verticalLayout_17.addWidget(self.lb_Vendasdiario)
        self.verticalLayout_13.addWidget(self.frame_14)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget_3.setMaximumSize(QtCore.QSize(300, 0))
        self.tableWidget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_3.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.tableWidget_3)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem16)
        self.horizontalLayout_10.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget_12)
        self.widget_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_15 = QtWidgets.QFrame(self.widget_2)
        self.frame_15.setMinimumSize(QtCore.QSize(300, 80))
        self.frame_15.setMaximumSize(QtCore.QSize(300, 80))
        self.frame_15.setStyleSheet("")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_18.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.bt_verestoque = QtWidgets.QPushButton(self.frame_15)
        self.bt_verestoque.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bt_verestoque.setCheckable(True)
        self.bt_verestoque.setObjectName("bt_verestoque")
        self.verticalLayout_18.addWidget(self.bt_verestoque)
        self.lb_quantEstoquediario = QtWidgets.QLabel(self.frame_15)
        self.lb_quantEstoquediario.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.lb_quantEstoquediario.setFont(font)
        self.lb_quantEstoquediario.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lb_quantEstoquediario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_quantEstoquediario.setObjectName("lb_quantEstoquediario")
        self.verticalLayout_18.addWidget(self.lb_quantEstoquediario)
        self.verticalLayout_12.addWidget(self.frame_15)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(300, 0))
        self.tableWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.verticalLayout_12.addWidget(self.tableWidget_2)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem17)
        self.horizontalLayout_10.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_12)
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_16 = QtWidgets.QFrame(self.widget)
        self.frame_16.setMinimumSize(QtCore.QSize(300, 80))
        self.frame_16.setMaximumSize(QtCore.QSize(300, 80))
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_19.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.clientes = QtWidgets.QPushButton(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.clientes.setFont(font)
        self.clientes.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clientes.setCheckable(True)
        self.clientes.setObjectName("clientes")
        self.verticalLayout_19.addWidget(self.clientes)
        self.lb_QuantClienteDiario = QtWidgets.QLabel(self.frame_16)
        self.lb_QuantClienteDiario.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.lb_QuantClienteDiario.setFont(font)
        self.lb_QuantClienteDiario.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lb_QuantClienteDiario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_QuantClienteDiario.setObjectName("lb_QuantClienteDiario")
        self.verticalLayout_19.addWidget(self.lb_QuantClienteDiario)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setMaximumSize(QtCore.QSize(300, 0))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_11.addWidget(self.tableWidget)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem18)
        self.horizontalLayout_10.addWidget(self.widget)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout_20.addWidget(self.widget_12)
        self.verticalLayout_3.addWidget(self.frame_11)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem20)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/window10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.inicialpage, icon18, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.horizontalLayout_3.addWidget(self.fundo)
        self.widlembrete = QtWidgets.QWidget(self.frame_3)
        self.widlembrete.setEnabled(True)
        self.widlembrete.setMinimumSize(QtCore.QSize(300, 0))
        self.widlembrete.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widlembrete.setStyleSheet("QWidget#widlembrete{border:none;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.widlembrete.setObjectName("widlembrete")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.widlembrete)
        self.verticalLayout_28.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_28.setSpacing(5)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_18 = QtWidgets.QFrame(self.widlembrete)
        self.frame_18.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton{\n"
"\n"
"    \n"
"border:none;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.bt_maislembrete = QtWidgets.QToolButton(self.frame_18)
        self.bt_maislembrete.setStyleSheet("background-color: none")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/novo/telainicial/mais.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maislembrete.setIcon(icon19)
        self.bt_maislembrete.setIconSize(QtCore.QSize(20, 20))
        self.bt_maislembrete.setObjectName("bt_maislembrete")
        self.horizontalLayout_12.addWidget(self.bt_maislembrete)
        self.label_7 = QtWidgets.QLabel(self.frame_18)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.bt_atulembrete = QtWidgets.QToolButton(self.frame_18)
        self.bt_atulembrete.setStyleSheet("background-color: none")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/novo/telainicial/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_atulembrete.setIcon(icon20)
        self.bt_atulembrete.setIconSize(QtCore.QSize(20, 20))
        self.bt_atulembrete.setObjectName("bt_atulembrete")
        self.horizontalLayout_12.addWidget(self.bt_atulembrete)
        self.verticalLayout_28.addWidget(self.frame_18)
        self.scrolllembrete = QtWidgets.QScrollArea(self.widlembrete)
        self.scrolllembrete.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"border:none;\n"
"}")
        self.scrolllembrete.setWidgetResizable(True)
        self.scrolllembrete.setObjectName("scrolllembrete")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 290, 622))
        self.scrollAreaWidgetContents_5.setStyleSheet("QTextEdit{padding:15px;font: 900 9pt Arial Black;line-height: 1.5;}")
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_29.setSpacing(8)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_5)
        self.widget_6.setStyleSheet("QScrollBar {\n"
"  \n"
"    background:  white;\n"
"    \n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(10)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.lembrete = QtWidgets.QVBoxLayout()
        self.lembrete.setObjectName("lembrete")
        self.verticalLayout_31.addLayout(self.lembrete)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_31.addItem(spacerItem21)
        self.verticalLayout_29.addWidget(self.widget_6)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem22)
        self.scrolllembrete.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_28.addWidget(self.scrolllembrete)
        self.horizontalLayout_3.addWidget(self.widlembrete)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"background-color:#005a9e;\n"
"}\n"
"QPushButton {\n"
"\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"border:none;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"\n"
"    background-color: #0864ae;\n"
"    }")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem23)
        self.bt_voltar = QtWidgets.QPushButton(self.frame_4)
        self.bt_voltar.setMinimumSize(QtCore.QSize(120, 0))
        self.bt_voltar.setMaximumSize(QtCore.QSize(120, 50))
        self.bt_voltar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_voltar.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/menuesquerda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_voltar.setIcon(icon21)
        self.bt_voltar.setIconSize(QtCore.QSize(40, 40))
        self.bt_voltar.setObjectName("bt_voltar")
        self.horizontalLayout.addWidget(self.bt_voltar)
        self.bt_CloseAbas = QtWidgets.QPushButton(self.frame_4)
        self.bt_CloseAbas.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/novo/telainicial/cancelarvenda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_CloseAbas.setIcon(icon22)
        self.bt_CloseAbas.setIconSize(QtCore.QSize(40, 40))
        self.bt_CloseAbas.setObjectName("bt_CloseAbas")
        self.horizontalLayout.addWidget(self.bt_CloseAbas)
        self.bt_seguir = QtWidgets.QPushButton(self.frame_4)
        self.bt_seguir.setMinimumSize(QtCore.QSize(120, 0))
        self.bt_seguir.setMaximumSize(QtCore.QSize(120, 50))
        self.bt_seguir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_seguir.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/setadireita.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_seguir.setIcon(icon23)
        self.bt_seguir.setIconSize(QtCore.QSize(41, 40))
        self.bt_seguir.setObjectName("bt_seguir")
        self.horizontalLayout.addWidget(self.bt_seguir)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem24)
        self.verticalLayout_4.addWidget(self.frame_4)
        Inicial.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Inicial)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusBar.setFont(font)
        self.statusBar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.statusBar.setObjectName("statusBar")
        Inicial.setStatusBar(self.statusBar)
        self.actionConfig = QtWidgets.QAction(Inicial)
        self.actionConfig.setIcon(icon7)
        self.actionConfig.setObjectName("actionConfig")
        self.actionok = QtWidgets.QAction(Inicial)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionok.setFont(font)
        self.actionok.setObjectName("actionok")
        self.actionIncluir_Parcelas = QtWidgets.QAction(Inicial)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/planopagamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionIncluir_Parcelas.setIcon(icon24)
        self.actionIncluir_Parcelas.setObjectName("actionIncluir_Parcelas")
        self.actionCadastro_Funcionario = QtWidgets.QAction(Inicial)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/funcionario.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastro_Funcionario.setIcon(icon25)
        self.actionCadastro_Funcionario.setObjectName("actionCadastro_Funcionario")
        self.actionDeslogar = QtWidgets.QAction(Inicial)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeslogar.setIcon(icon26)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actionDeslogar.setFont(font)
        self.actionDeslogar.setMenuRole(QtWidgets.QAction.PreferencesRole)
        self.actionDeslogar.setPriority(QtWidgets.QAction.HighPriority)
        self.actionDeslogar.setObjectName("actionDeslogar")
        self.actionCADASTRO_DE_USUARIO = QtWidgets.QAction(Inicial)
        self.actionCADASTRO_DE_USUARIO.setIcon(icon25)
        self.actionCADASTRO_DE_USUARIO.setObjectName("actionCADASTRO_DE_USUARIO")
        self.actionincluir_tipo_documento = QtWidgets.QAction(Inicial)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/contasapagar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionincluir_tipo_documento.setIcon(icon27)
        self.actionincluir_tipo_documento.setObjectName("actionincluir_tipo_documento")
        self.actioncadastro_fornecedor = QtWidgets.QAction(Inicial)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/fornecedor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncadastro_fornecedor.setIcon(icon28)
        self.actioncadastro_fornecedor.setObjectName("actioncadastro_fornecedor")
        self.actioncadastro_de_tributo = QtWidgets.QAction(Inicial)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/tributosbranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncadastro_de_tributo.setIcon(icon29)
        self.actioncadastro_de_tributo.setObjectName("actioncadastro_de_tributo")
        self.actionFECHAR = QtWidgets.QAction(Inicial)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFECHAR.setIcon(icon30)
        self.actionFECHAR.setObjectName("actionFECHAR")
        self.actionclientes = QtWidgets.QAction(Inicial)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/cadastro clientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionclientes.setIcon(icon31)
        self.actionclientes.setObjectName("actionclientes")
        self.actionestoque = QtWidgets.QAction(Inicial)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/estoque.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionestoque.setIcon(icon32)
        self.actionestoque.setObjectName("actionestoque")
        self.actionconta_apagar = QtWidgets.QAction(Inicial)
        self.actionconta_apagar.setIcon(icon27)
        self.actionconta_apagar.setObjectName("actionconta_apagar")
        self.actionconta_receber = QtWidgets.QAction(Inicial)
        self.actionconta_receber.setIcon(icon5)
        self.actionconta_receber.setObjectName("actionconta_receber")
        self.actioncaixa = QtWidgets.QAction(Inicial)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/caixa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncaixa.setIcon(icon33)
        self.actioncaixa.setObjectName("actioncaixa")
        self.actionentrada_de_nota = QtWidgets.QAction(Inicial)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/entradanota.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionentrada_de_nota.setIcon(icon34)
        self.actionentrada_de_nota.setObjectName("actionentrada_de_nota")
        self.actionanalise_de_vendas = QtWidgets.QAction(Inicial)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/analytics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionanalise_de_vendas.setIcon(icon35)
        self.actionanalise_de_vendas.setObjectName("actionanalise_de_vendas")
        self.actionpdv = QtWidgets.QAction(Inicial)
        self.actionpdv.setIcon(icon4)
        self.actionpdv.setObjectName("actionpdv")
        self.actionPRodutos_por_grupo = QtWidgets.QAction(Inicial)
        self.actionPRodutos_por_grupo.setObjectName("actionPRodutos_por_grupo")
        self.actioncadastro_grupo = QtWidgets.QAction(Inicial)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/grupoprodutobranco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncadastro_grupo.setIcon(icon36)
        self.actioncadastro_grupo.setObjectName("actioncadastro_grupo")
        self.actioncadastro_estoque = QtWidgets.QAction(Inicial)
        self.actioncadastro_estoque.setIcon(icon10)
        self.actioncadastro_estoque.setObjectName("actioncadastro_estoque")
        self.actioncadastro_clientes = QtWidgets.QAction(Inicial)
        self.actioncadastro_clientes.setIcon(icon11)
        self.actioncadastro_clientes.setObjectName("actioncadastro_clientes")
        self.actionpdv_restaurante = QtWidgets.QAction(Inicial)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/restaurante.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpdv_restaurante.setIcon(icon37)
        self.actionpdv_restaurante.setObjectName("actionpdv_restaurante")
        self.actionbuckp_sistema = QtWidgets.QAction(Inicial)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/backp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionbuckp_sistema.setIcon(icon38)
        self.actionbuckp_sistema.setObjectName("actionbuckp_sistema")

        self.retranslateUi(Inicial)
        self.tabWidget.setCurrentIndex(0)
        self.bt_minimize.clicked['bool'].connect(Inicial.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Inicial)

    def retranslateUi(self, Inicial):
        _translate = QtCore.QCoreApplication.translate
        Inicial.setWindowTitle(_translate("Inicial", "SOFTHOUSE"))
        self.label.setText(_translate("Inicial", "seja Bem vindo"))
        self.bt_closer.setShortcut(_translate("Inicial", "Esc"))
        self.tollcadastro.setText(_translate("Inicial", "cadastros"))
        self.tb_vendas.setText(_translate("Inicial", "vendas"))
        self.toolfinanceiro.setText(_translate("Inicial", "financeiro"))
        self.tollutitilitarios.setText(_translate("Inicial", "utilitarios"))
        self.tolconfiguracao.setText(_translate("Inicial", "configuraçaoes"))
        self.bt_Menu.setToolTip(_translate("Inicial", "<html><head/><body><p>MENU BOTOES</p></body></html>"))
        self.bt_Menu.setStatusTip(_translate("Inicial", "menu botoes"))
        self.bt_Cadastros.setText(_translate("Inicial", "cadastro"))
        self.bt_estoqque.setText(_translate("Inicial", "estoque"))
        self.bt_clientes.setText(_translate("Inicial", "clientes"))
        self.bt_funcionario.setText(_translate("Inicial", "cadastro Funcionario"))
        self.BtFinanceiros.setText(_translate("Inicial", "financeiro"))
        self.tb_receber.setText(_translate("Inicial", "receber"))
        self.tb_caixa.setText(_translate("Inicial", "caixa"))
        self.tb_pagarConta.setText(_translate("Inicial", "contas apagar"))
        self.bt_entradasnotas.setText(_translate("Inicial", "entrada de nota"))
        self.tb_entradanota.setText(_translate("Inicial", "entrada de nota"))
        self.Bt_vendas.setText(_translate("Inicial", "vendas"))
        self.tb_analasivenda.setText(_translate("Inicial", "analise vendas"))
        self.label_4.setText(_translate("Inicial", "relatorio geral"))
        self.label_6.setText(_translate("Inicial", "valor caixa"))
        self.label_5.setText(_translate("Inicial", "vendas"))
        self.lb_Vendas.setText(_translate("Inicial", "0"))
        self.label_3.setText(_translate("Inicial", "estoque"))
        self.lb_quantEstoque.setText(_translate("Inicial", "0"))
        self.label_2.setText(_translate("Inicial", "Clientes"))
        self.lb_quantClientes.setText(_translate("Inicial", "0"))
        self.label_16.setText(_translate("Inicial", "relatorio diario"))
        self.dataRelatorio.setDisplayFormat(_translate("Inicial", "dd/MM/yyyy"))
        self.bt_caixa.setText(_translate("Inicial", "caixa"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Inicial", "descricaçao"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Inicial", "valor"))
        self.bt_vervenda.setText(_translate("Inicial", "vendas"))
        self.lb_Vendasdiario.setText(_translate("Inicial", "0"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Inicial", "cod"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Inicial", "descriçao"))
        self.bt_verestoque.setText(_translate("Inicial", "estoque"))
        self.lb_quantEstoquediario.setText(_translate("Inicial", "0"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Inicial", "cod"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Inicial", "descriçao"))
        self.clientes.setText(_translate("Inicial", "clientes"))
        self.lb_QuantClienteDiario.setText(_translate("Inicial", "0"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Inicial", "cod"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Inicial", "descriçao"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inicialpage), _translate("Inicial", "Inicial Sistema"))
        self.bt_maislembrete.setText(_translate("Inicial", "..."))
        self.label_7.setText(_translate("Inicial", "lembrete sistema"))
        self.bt_atulembrete.setText(_translate("Inicial", "..."))
        self.actionConfig.setText(_translate("Inicial", "Config"))
        self.actionok.setText(_translate("Inicial", "ok"))
        self.actionIncluir_Parcelas.setText(_translate("Inicial", "plano pagamento /parcelas"))
        self.actionCadastro_Funcionario.setText(_translate("Inicial", "Cadastro Funcionarios"))
        self.actionDeslogar.setText(_translate("Inicial", "Deslogar"))
        self.actionDeslogar.setToolTip(_translate("Inicial", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#55aaff; background-color:#ffffff;\">Deslogar</span><img src=\":/telainicial/telainicial/ajuda.png\"/></p></body></html>"))
        self.actionDeslogar.setStatusTip(_translate("Inicial", "deslogar"))
        self.actionCADASTRO_DE_USUARIO.setText(_translate("Inicial", "CADASTRO DE USUARIO"))
        self.actionincluir_tipo_documento.setText(_translate("Inicial", "incluir tipo documento"))
        self.actioncadastro_fornecedor.setText(_translate("Inicial", "cadastro fornecedor"))
        self.actioncadastro_de_tributo.setText(_translate("Inicial", "cadastro de tributo"))
        self.actionFECHAR.setText(_translate("Inicial", "FECHAR"))
        self.actionclientes.setText(_translate("Inicial", "clientes"))
        self.actionestoque.setText(_translate("Inicial", "estoque"))
        self.actionconta_apagar.setText(_translate("Inicial", "conta apagar"))
        self.actionconta_receber.setText(_translate("Inicial", "receber"))
        self.actioncaixa.setText(_translate("Inicial", "caixa"))
        self.actionentrada_de_nota.setText(_translate("Inicial", "entrada de nota"))
        self.actionanalise_de_vendas.setText(_translate("Inicial", "analise de vendas"))
        self.actionpdv.setText(_translate("Inicial", "pdv"))
        self.actionPRodutos_por_grupo.setText(_translate("Inicial", "PRodutos por grupo"))
        self.actioncadastro_grupo.setText(_translate("Inicial", "cadastro grupos"))
        self.actioncadastro_estoque.setText(_translate("Inicial", "cadastro estoque"))
        self.actioncadastro_clientes.setText(_translate("Inicial", "cadastro clientes"))
        self.actionpdv_restaurante.setText(_translate("Inicial", "pdv restaurante"))
        self.actionbuckp_sistema.setText(_translate("Inicial", "buckp sistema"))
