# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormLyoute/MAINPDV.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDV(object):
    def setupUi(self, PDV):
        PDV.setObjectName("PDV")
        PDV.setWindowModality(QtCore.Qt.ApplicationModal)
        PDV.resize(2254, 885)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/pdv.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PDV.setWindowIcon(icon)
        PDV.setStyleSheet("QWidget{\n"
"text-transform: uppercase;\n"
"        background-color:#005a9e;\n"
"}\n"
"\n"
"QToolTip {\n"
"text-transform: uppercase;\n"
"    border: 2px solid green;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"    background-image: url(images/welcome.png);\n"
"color :black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(PDV)
        self.verticalLayout.setContentsMargins(1, 1, 1, 4)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topdados = QtWidgets.QFrame(PDV)
        self.topdados.setMinimumSize(QtCore.QSize(0, 0))
        self.topdados.setStyleSheet("QFrame#topdados{\n"
"background-color: rgb(15, 138, 77);\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton {\n"
"        background-color:#005a9e;\n"
"        color: white;\n"
"        font-weight: bold;\n"
"        padding: 5px;\n"
"border:none;\n"
"    }\n"
"    QPushButton:hover {\n"
"    background-color: #0864ae;\n"
"    }\n"
"QPushButton:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:1 rgba(255, 255, 255, 111));\n"
"}")
        self.topdados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topdados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topdados.setObjectName("topdados")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.topdados)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.topdados)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"        background-color:#005a9e;\n"
"border :3px solid #005a9e;\n"
" border-top-left-radius :0px;\n"
"border-top-right-radius : 0px; \n"
" border-bottom-left-radius : 0px;\n"
" border-bottom-right-radius :25px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
" background-color:#005a9e;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_15.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_15.setSpacing(1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tx_DescricaoITemTab = QtWidgets.QLineEdit(self.frame_17)
        self.tx_DescricaoITemTab.setMinimumSize(QtCore.QSize(0, 50))
        self.tx_DescricaoITemTab.setMouseTracking(True)
        self.tx_DescricaoITemTab.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_DescricaoITemTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tx_DescricaoITemTab.setStyleSheet("QLineEdit{\n"
"background:transparent;\n"
"border-radius: 0px;\n"
"    color: white;\n"
"font: 33px \"Arial\" ;\n"
"font-weight: bold;\n"
"padding:5px 35px;\n"
"}\n"
"\n"
"")
        self.tx_DescricaoITemTab.setText("")
        self.tx_DescricaoITemTab.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_DescricaoITemTab.setReadOnly(False)
        self.tx_DescricaoITemTab.setPlaceholderText("")
        self.tx_DescricaoITemTab.setObjectName("tx_DescricaoITemTab")
        self.horizontalLayout_15.addWidget(self.tx_DescricaoITemTab)
        self.horizontalLayout_14.addWidget(self.frame_17)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.Lb_caixaOcupado = QtWidgets.QLabel(self.topdados)
        self.Lb_caixaOcupado.setMinimumSize(QtCore.QSize(0, 0))
        self.Lb_caixaOcupado.setMaximumSize(QtCore.QSize(500, 16777215))
        self.Lb_caixaOcupado.setStyleSheet("background-color: none;\n"
"font: 87 20pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.Lb_caixaOcupado.setAlignment(QtCore.Qt.AlignCenter)
        self.Lb_caixaOcupado.setObjectName("Lb_caixaOcupado")
        self.horizontalLayout_14.addWidget(self.Lb_caixaOcupado)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.frame_10 = QtWidgets.QFrame(self.topdados)
        self.frame_10.setMinimumSize(QtCore.QSize(120, 0))
        self.frame_10.setStyleSheet("QFrame{\n"
"            background-color:#005a9e;\n"
"border :3px solid #005a9e;\n"
" border-top-left-radius :0px;\n"
"border-top-right-radius : 0px; \n"
" border-bottom-left-radius : 25px;\n"
" border-bottom-right-radius : 0px;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_17.setContentsMargins(9, 9, 9, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.bt_cancelar = QtWidgets.QPushButton(self.frame_10)
        self.bt_cancelar.setMinimumSize(QtCore.QSize(35, 35))
        self.bt_cancelar.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.bt_cancelar.setFont(font)
        self.bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_cancelar.setStyleSheet("\n"
"QPushButton {\n"
"    \n"
"\n"
"padding:5px 5px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius:6px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(218, 218, 218);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(249, 249, 52);\n"
"}")
        self.bt_cancelar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/novobranco/telainicial/menuopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cancelar.setIcon(icon1)
        self.bt_cancelar.setIconSize(QtCore.QSize(20, 20))
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.horizontalLayout_17.addWidget(self.bt_cancelar)
        self.horizontalLayout_14.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.topdados)
        self.fr_FormVenda = QtWidgets.QFrame(PDV)
        self.fr_FormVenda.setStyleSheet("QFrame{\n"
"        background-color:#005a9e;\n"
"border: none\n"
"}")
        self.fr_FormVenda.setObjectName("fr_FormVenda")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.fr_FormVenda)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.fr_FormVenda)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setMinimumSize(QtCore.QSize(170, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fraTop = QtWidgets.QFrame(self.frame_2)
        self.fraTop.setStyleSheet("QFrame{\n"
"background: #FFF;\n"
"\n"
"}\n"
"")
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.fraTop)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3.addWidget(self.fraTop)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setStyleSheet("QFrame{\n"
"        background-color:#005a9e;\n"
"border: 0px solid #1E87F0;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(10, 2, 2, 3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setStyleSheet("border:none")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"    color: rgb(255, 255, 255);\n"
"border: none\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"    color: rgb(255, 255, 255);\n"
"border: none\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("border:none")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tx_codigoCliente = QtWidgets.QLineEdit(self.frame_5)
        self.tx_codigoCliente.setMinimumSize(QtCore.QSize(90, 39))
        self.tx_codigoCliente.setMaximumSize(QtCore.QSize(150, 16777215))
        self.tx_codigoCliente.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tx_codigoCliente.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tx_codigoCliente.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"padding:10px\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);r\n"
"}")
        self.tx_codigoCliente.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_codigoCliente.setObjectName("tx_codigoCliente")
        self.horizontalLayout_2.addWidget(self.tx_codigoCliente)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.tx_nomeCliente = QtWidgets.QLineEdit(self.frame_5)
        self.tx_nomeCliente.setMinimumSize(QtCore.QSize(150, 0))
        self.tx_nomeCliente.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tx_nomeCliente.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tx_nomeCliente.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 15px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"padding:10px\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);r\n"
"}")
        self.tx_nomeCliente.setText("")
        self.tx_nomeCliente.setObjectName("tx_nomeCliente")
        self.horizontalLayout_2.addWidget(self.tx_nomeCliente)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame)
        self.fr_addProduto = QtWidgets.QFrame(self.frame_2)
        self.fr_addProduto.setStyleSheet("QFrame{\n"
"        background-color:#005a9e;\n"
"border: 0px solid #1E87F0;\n"
"}\n"
"")
        self.fr_addProduto.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_addProduto.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fr_addProduto.setObjectName("fr_addProduto")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fr_addProduto)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.db_Quantidade = QtWidgets.QSpinBox(self.fr_addProduto)
        self.db_Quantidade.setMinimumSize(QtCore.QSize(0, 47))
        self.db_Quantidade.setFocusPolicy(QtCore.Qt.TabFocus)
        self.db_Quantidade.setStyleSheet("background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 25px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"padding:5px")
        self.db_Quantidade.setAlignment(QtCore.Qt.AlignCenter)
        self.db_Quantidade.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_Quantidade.setKeyboardTracking(True)
        self.db_Quantidade.setMaximum(1200)
        self.db_Quantidade.setProperty("value", 1)
        self.db_Quantidade.setObjectName("db_Quantidade")
        self.horizontalLayout_5.addWidget(self.db_Quantidade)
        self.tx_BuscaItem_2 = QtWidgets.QLineEdit(self.fr_addProduto)
        self.tx_BuscaItem_2.setMouseTracking(True)
        self.tx_BuscaItem_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tx_BuscaItem_2.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"padding:15px\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"    background-color: rgb(255, 255, 255);r\n"
"}")
        self.tx_BuscaItem_2.setText("")
        self.tx_BuscaItem_2.setFrame(False)
        self.tx_BuscaItem_2.setCursorPosition(0)
        self.tx_BuscaItem_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tx_BuscaItem_2.setReadOnly(False)
        self.tx_BuscaItem_2.setObjectName("tx_BuscaItem_2")
        self.horizontalLayout_5.addWidget(self.tx_BuscaItem_2)
        self.verticalLayout_3.addWidget(self.fr_addProduto)
        self.tb_Itens = QtWidgets.QTableWidget(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.tb_Itens.setFont(font)
        self.tb_Itens.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tb_Itens.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tb_Itens.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tb_Itens.setStyleSheet("QTableView{\n"
"background: #F1F1F1;\n"
"color: black;\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"border:1px solid blakc;\n"
"    \n"
"    selection-color: rgb(255, 0, 0);\n"
"    selection-background-color: rgb(85, 170, 255);\n"
"}\n"
"QHeaderView:section{\n"
"background: #FFF;\n"
"\n"
"font-size: 13px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: #797979;\n"
"border:none;\n"
"border-bottom: 2px solid black;\n"
"border-top:2px solid black;\n"
"padding:5px 0px;\n"
"text-transform: uppercase\n"
"}\n"
"\n"
"\n"
"")
        self.tb_Itens.setAutoScrollMargin(20)
        self.tb_Itens.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_Itens.setTabKeyNavigation(False)
        self.tb_Itens.setProperty("showDropIndicator", False)
        self.tb_Itens.setDragDropOverwriteMode(False)
        self.tb_Itens.setAlternatingRowColors(True)
        self.tb_Itens.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tb_Itens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_Itens.setShowGrid(True)
        self.tb_Itens.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tb_Itens.setWordWrap(True)
        self.tb_Itens.setObjectName("tb_Itens")
        self.tb_Itens.setColumnCount(6)
        self.tb_Itens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tb_Itens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tb_Itens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tb_Itens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Itens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Itens.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_Itens.setHorizontalHeaderItem(5, item)
        self.tb_Itens.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_Itens.horizontalHeader().setDefaultSectionSize(180)
        self.tb_Itens.horizontalHeader().setHighlightSections(True)
        self.tb_Itens.horizontalHeader().setSortIndicatorShown(False)
        self.tb_Itens.horizontalHeader().setStretchLastSection(False)
        self.tb_Itens.verticalHeader().setVisible(False)
        self.tb_Itens.verticalHeader().setDefaultSectionSize(50)
        self.tb_Itens.verticalHeader().setHighlightSections(True)
        self.tb_Itens.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.tb_Itens)
        self.Quantidadetela = QtWidgets.QLabel(self.frame_2)
        self.Quantidadetela.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background:none;")
        self.Quantidadetela.setText("")
        self.Quantidadetela.setObjectName("Quantidadetela")
        self.verticalLayout_3.addWidget(self.Quantidadetela)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:1, stop:1 rgba(255, 0, 0, 216));\n"
"}\n"
"QLabel{\n"
"font-size: 10px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setStyleSheet("QFrame{\n"
"    background-color: none;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.frame_12)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 60))
        self.frame_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_15.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: white;\n"
"border: none;\n"
"\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tx_codigovendedor = QtWidgets.QLabel(self.frame_15)
        self.tx_codigovendedor.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tx_codigovendedor.setObjectName("tx_codigovendedor")
        self.horizontalLayout_7.addWidget(self.tx_codigovendedor)
        self.tx_NomeVendedor = QtWidgets.QLabel(self.frame_15)
        self.tx_NomeVendedor.setObjectName("tx_NomeVendedor")
        self.horizontalLayout_7.addWidget(self.tx_NomeVendedor)
        self.verticalLayout_12.addWidget(self.frame_15)
        self.horizontalLayout_11.addWidget(self.frame_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lb_FormVenda_29 = QtWidgets.QLabel(self.frame_13)
        self.lb_FormVenda_29.setMinimumSize(QtCore.QSize(0, 20))
        self.lb_FormVenda_29.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lb_FormVenda_29.setStyleSheet("")
        self.lb_FormVenda_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_FormVenda_29.setObjectName("lb_FormVenda_29")
        self.verticalLayout_10.addWidget(self.lb_FormVenda_29)
        self.tx_quantidadeitem = QtWidgets.QLabel(self.frame_13)
        self.tx_quantidadeitem.setMinimumSize(QtCore.QSize(0, 20))
        self.tx_quantidadeitem.setStyleSheet("\n"
"font-size: 15px;")
        self.tx_quantidadeitem.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_quantidadeitem.setObjectName("tx_quantidadeitem")
        self.verticalLayout_10.addWidget(self.tx_quantidadeitem)
        self.horizontalLayout_11.addWidget(self.frame_13)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lb_FormVenda_28 = QtWidgets.QLabel(self.frame_14)
        self.lb_FormVenda_28.setMinimumSize(QtCore.QSize(0, 20))
        self.lb_FormVenda_28.setStyleSheet("")
        self.lb_FormVenda_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_FormVenda_28.setObjectName("lb_FormVenda_28")
        self.verticalLayout_11.addWidget(self.lb_FormVenda_28)
        self.db_ValorTotalvenda = QtWidgets.QDoubleSpinBox(self.frame_14)
        self.db_ValorTotalvenda.setMinimumSize(QtCore.QSize(0, 20))
        self.db_ValorTotalvenda.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_ValorTotalvenda.setStyleSheet("\n"
"font-size: 15px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color:white;\n"
"border: none;\n"
"background: transparent;\n"
"")
        self.db_ValorTotalvenda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.db_ValorTotalvenda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_ValorTotalvenda.setProperty("showGroupSeparator", True)
        self.db_ValorTotalvenda.setMaximum(9999999.0)
        self.db_ValorTotalvenda.setObjectName("db_ValorTotalvenda")
        self.verticalLayout_11.addWidget(self.db_ValorTotalvenda)
        self.horizontalLayout_11.addWidget(self.frame_14)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.fr_financeiroPedido = QtWidgets.QFrame(self.frame_3)
        self.fr_financeiroPedido.setMinimumSize(QtCore.QSize(320, 0))
        self.fr_financeiroPedido.setMaximumSize(QtCore.QSize(320, 16777215))
        self.fr_financeiroPedido.setStyleSheet("QFrame{\n"
"border-top: 4px solid #277298;\n"
"border-bottom: 4px solid #277298;\n"
"border:none;}\n"
"QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/newPrefix/icons8_expand_arrow.svg);\n"
" }\n"
"")
        self.fr_financeiroPedido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_financeiroPedido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_financeiroPedido.setObjectName("fr_financeiroPedido")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fr_financeiroPedido)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_9 = QtWidgets.QFrame(self.fr_financeiroPedido)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.lb_fotosEstoque = QtWidgets.QLabel(self.frame_9)
        self.lb_fotosEstoque.setMinimumSize(QtCore.QSize(200, 200))
        self.lb_fotosEstoque.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lb_fotosEstoque.setStyleSheet("QLabel{background: transparent;\n"
"border:none;}")
        self.lb_fotosEstoque.setText("")
        self.lb_fotosEstoque.setPixmap(QtGui.QPixmap(":/newPrefix/img/profile.png"))
        self.lb_fotosEstoque.setScaledContents(True)
        self.lb_fotosEstoque.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_fotosEstoque.setObjectName("lb_fotosEstoque")
        self.horizontalLayout_13.addWidget(self.lb_fotosEstoque)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.fr_financeiroPedido)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6.addWidget(self.frame_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.lb_propaganda = QtWidgets.QLabel(self.fr_financeiroPedido)
        self.lb_propaganda.setMinimumSize(QtCore.QSize(0, 200))
        self.lb_propaganda.setStyleSheet("")
        self.lb_propaganda.setText("")
        self.lb_propaganda.setScaledContents(True)
        self.lb_propaganda.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_propaganda.setObjectName("lb_propaganda")
        self.verticalLayout_6.addWidget(self.lb_propaganda)
        self.horizontalLayout_6.addWidget(self.fr_financeiroPedido)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.fr_FormVenda)
        self.fr_topoPedido = QtWidgets.QFrame(PDV)
        self.fr_topoPedido.setStyleSheet("QFrame{\n"
"        background-color:#005a9e;\n"
"border:none;\n"
"}\n"
"")
        self.fr_topoPedido.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fr_topoPedido.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fr_topoPedido.setObjectName("fr_topoPedido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_topoPedido)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fr_BotoesFormVenda = QtWidgets.QFrame(self.fr_topoPedido)
        self.fr_BotoesFormVenda.setMaximumSize(QtCore.QSize(16777215, 60))
        self.fr_BotoesFormVenda.setStyleSheet("QFrame{        background-color:#005a9e;\n"
"border: none;\n"
"}\n"
"QPushButton {\n"
"\n"
"color: white;\n"
"padding:0px 5px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-radius:6px\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(218, 218, 218);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(249, 249, 52);\n"
"}")
        self.fr_BotoesFormVenda.setObjectName("fr_BotoesFormVenda")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_BotoesFormVenda)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_finalizar = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.bt_finalizar.setFont(font)
        self.bt_finalizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_finalizar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_finalizar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.bt_finalizar.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/contasapagar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_finalizar.setIcon(icon2)
        self.bt_finalizar.setIconSize(QtCore.QSize(20, 20))
        self.bt_finalizar.setObjectName("bt_finalizar")
        self.horizontalLayout.addWidget(self.bt_finalizar)
        self.bt_imprimir = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        self.bt_imprimir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_imprimir.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/impressao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_imprimir.setIcon(icon3)
        self.bt_imprimir.setIconSize(QtCore.QSize(20, 20))
        self.bt_imprimir.setObjectName("bt_imprimir")
        self.horizontalLayout.addWidget(self.bt_imprimir)
        self.bt_configura = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        self.bt_configura.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_configura.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_configura.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/configura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_configura.setIcon(icon4)
        self.bt_configura.setIconSize(QtCore.QSize(20, 20))
        self.bt_configura.setObjectName("bt_configura")
        self.horizontalLayout.addWidget(self.bt_configura)
        self.bt_orca = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        self.bt_orca.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_orca.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_orca.setAutoFillBackground(False)
        self.bt_orca.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/orcamento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_orca.setIcon(icon5)
        self.bt_orca.setIconSize(QtCore.QSize(20, 20))
        self.bt_orca.setObjectName("bt_orca")
        self.horizontalLayout.addWidget(self.bt_orca)
        self.bt_SalvaORcas = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        self.bt_SalvaORcas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_SalvaORcas.setStyleSheet("")
        self.bt_SalvaORcas.setIcon(icon5)
        self.bt_SalvaORcas.setIconSize(QtCore.QSize(20, 20))
        self.bt_SalvaORcas.setObjectName("bt_SalvaORcas")
        self.horizontalLayout.addWidget(self.bt_SalvaORcas)
        self.bt_Abricaixa = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        self.bt_Abricaixa.setFocusPolicy(QtCore.Qt.NoFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/caixa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_Abricaixa.setIcon(icon6)
        self.bt_Abricaixa.setIconSize(QtCore.QSize(20, 20))
        self.bt_Abricaixa.setObjectName("bt_Abricaixa")
        self.horizontalLayout.addWidget(self.bt_Abricaixa)
        self.bt_ajuda = QtWidgets.QPushButton(self.fr_BotoesFormVenda)
        self.bt_ajuda.setMinimumSize(QtCore.QSize(0, 0))
        self.bt_ajuda.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bt_ajuda.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_ajuda.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/ajuda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_ajuda.setIcon(icon7)
        self.bt_ajuda.setIconSize(QtCore.QSize(20, 20))
        self.bt_ajuda.setObjectName("bt_ajuda")
        self.horizontalLayout.addWidget(self.bt_ajuda)
        self.horizontalLayout_3.addWidget(self.fr_BotoesFormVenda)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.tx_pedidonumb = QtWidgets.QLineEdit(self.fr_topoPedido)
        self.tx_pedidonumb.setMinimumSize(QtCore.QSize(0, 30))
        self.tx_pedidonumb.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tx_pedidonumb.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_pedidonumb.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(227, 227, 227);\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 16px \"Arial\" ;\n"
"font-weight: bold;\n"
"\n"
"padding:5px\n"
"}\n"
"")
        self.tx_pedidonumb.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_pedidonumb.setReadOnly(False)
        self.tx_pedidonumb.setObjectName("tx_pedidonumb")
        self.horizontalLayout_3.addWidget(self.tx_pedidonumb)
        self.lb_FormVenda_25 = QtWidgets.QLabel(self.fr_topoPedido)
        self.lb_FormVenda_25.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"\n"
"color:white;\n"
"border: none;\n"
"}")
        self.lb_FormVenda_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_FormVenda_25.setObjectName("lb_FormVenda_25")
        self.horizontalLayout_3.addWidget(self.lb_FormVenda_25)
        self.tx_data = QtWidgets.QLineEdit(self.fr_topoPedido)
        self.tx_data.setMinimumSize(QtCore.QSize(0, 30))
        self.tx_data.setMaximumSize(QtCore.QSize(120, 16777215))
        self.tx_data.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_data.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(227, 227, 227);\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 16px \"Arial\" ;\n"
"font-weight: bold;\n"
"\n"
"padding:5px\n"
"}\n"
"")
        self.tx_data.setMaxLength(12)
        self.tx_data.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_data.setObjectName("tx_data")
        self.horizontalLayout_3.addWidget(self.tx_data)
        self.label_3 = QtWidgets.QLabel(self.fr_topoPedido)
        self.label_3.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"\n"
"color:white;\n"
"border: none;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tx_Horas = QtWidgets.QLineEdit(self.fr_topoPedido)
        self.tx_Horas.setMinimumSize(QtCore.QSize(0, 30))
        self.tx_Horas.setMaximumSize(QtCore.QSize(120, 16777215))
        self.tx_Horas.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tx_Horas.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(227, 227, 227);\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 16px \"Arial\" ;\n"
"font-weight: bold;\n"
"\n"
"padding:5px\n"
"}\n"
"")
        self.tx_Horas.setMaxLength(8)
        self.tx_Horas.setAlignment(QtCore.Qt.AlignCenter)
        self.tx_Horas.setObjectName("tx_Horas")
        self.horizontalLayout_3.addWidget(self.tx_Horas)
        self.verticalLayout.addWidget(self.fr_topoPedido)
        self.actionChamaCliente = QtWidgets.QAction(PDV)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/cadastro clientes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChamaCliente.setIcon(icon8)
        self.actionChamaCliente.setObjectName("actionChamaCliente")
        self.actionBUSCA_PRODUTO = QtWidgets.QAction(PDV)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/telainicial/telainicial/buscarproduto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBUSCA_PRODUTO.setIcon(icon9)
        self.actionBUSCA_PRODUTO.setObjectName("actionBUSCA_PRODUTO")

        self.retranslateUi(PDV)
        QtCore.QMetaObject.connectSlotsByName(PDV)
        PDV.setTabOrder(self.tx_BuscaItem_2, self.tb_Itens)

    def retranslateUi(self, PDV):
        _translate = QtCore.QCoreApplication.translate
        PDV.setWindowTitle(_translate("PDV", "PDV"))
        self.Lb_caixaOcupado.setText(_translate("PDV", "CAIXA LIVRE"))
        self.bt_cancelar.setShortcut(_translate("PDV", "Esc"))
        self.label.setText(_translate("PDV", "CLIENTES ( F11)"))
        self.label_2.setText(_translate("PDV", "NOME cliente"))
        self.tx_codigoCliente.setText(_translate("PDV", "0"))
        self.tx_codigoCliente.setPlaceholderText(_translate("PDV", "codigo"))
        self.tx_nomeCliente.setPlaceholderText(_translate("PDV", "nome cliente"))
        self.tx_BuscaItem_2.setPlaceholderText(_translate("PDV", "DIGITE O NOME  DO ITEM"))
        self.tb_Itens.setSortingEnabled(False)
        item = self.tb_Itens.horizontalHeaderItem(0)
        item.setText(_translate("PDV", "COD"))
        item = self.tb_Itens.horizontalHeaderItem(1)
        item.setText(_translate("PDV", "DESCRIÇAO"))
        item = self.tb_Itens.horizontalHeaderItem(2)
        item.setText(_translate("PDV", "QUANT"))
        item = self.tb_Itens.horizontalHeaderItem(3)
        item.setText(_translate("PDV", "VL UNIT"))
        item = self.tb_Itens.horizontalHeaderItem(4)
        item.setText(_translate("PDV", "VL TOTAL"))
        item = self.tb_Itens.horizontalHeaderItem(5)
        item.setText(_translate("PDV", "TIPO"))
        self.label_4.setText(_translate("PDV", "nome vendedor"))
        self.tx_codigovendedor.setText(_translate("PDV", "cod"))
        self.tx_NomeVendedor.setText(_translate("PDV", "nome"))
        self.lb_FormVenda_29.setText(_translate("PDV", "QUANt pro"))
        self.tx_quantidadeitem.setText(_translate("PDV", "0"))
        self.lb_FormVenda_28.setText(_translate("PDV", "TOTAL apagar (r$):"))
        self.bt_finalizar.setText(_translate("PDV", "finalizar (F2)"))
        self.bt_finalizar.setShortcut(_translate("PDV", "F2"))
        self.bt_imprimir.setText(_translate("PDV", "IMPRIMIR (ctrl+p)"))
        self.bt_configura.setText(_translate("PDV", "config"))
        self.bt_configura.setShortcut(_translate("PDV", "Ctrl+F3"))
        self.bt_orca.setText(_translate("PDV", "LEITURA (F7)"))
        self.bt_orca.setShortcut(_translate("PDV", "F7"))
        self.bt_SalvaORcas.setText(_translate("PDV", "SALVAR (F10)"))
        self.bt_SalvaORcas.setShortcut(_translate("PDV", "F10"))
        self.bt_Abricaixa.setText(_translate("PDV", "abrir caixa (f4)"))
        self.bt_Abricaixa.setShortcut(_translate("PDV", "F4"))
        self.bt_ajuda.setText(_translate("PDV", "ajuda (f1)"))
        self.bt_ajuda.setShortcut(_translate("PDV", "F1"))
        self.lb_FormVenda_25.setText(_translate("PDV", "DATA "))
        self.label_3.setText(_translate("PDV", "horas"))
        self.actionChamaCliente.setText(_translate("PDV", "ChamaCliente"))
        self.actionChamaCliente.setShortcut(_translate("PDV", "F11"))
        self.actionBUSCA_PRODUTO.setText(_translate("PDV", "BUSCA PRODUTO"))
        self.actionBUSCA_PRODUTO.setShortcut(_translate("PDV", "Ctrl+E"))

